/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ble_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(onecollar_ble_v1_ToCollar, onecollar_ble_v1_ToCollar, 2)


PB_BIND(onecollar_ble_v1_FromCollar, onecollar_ble_v1_FromCollar, 4)


PB_BIND(onecollar_ble_v1_Event, onecollar_ble_v1_Event, AUTO)


PB_BIND(onecollar_ble_v1_ImuBatch, onecollar_ble_v1_ImuBatch, 2)


PB_BIND(onecollar_ble_v1_GetCapabilitiesRequest, onecollar_ble_v1_GetCapabilitiesRequest, AUTO)


PB_BIND(onecollar_ble_v1_Capabilities, onecollar_ble_v1_Capabilities, 4)


PB_BIND(onecollar_ble_v1_Capability, onecollar_ble_v1_Capability, AUTO)


PB_BIND(onecollar_ble_v1_GetBatteryRequest, onecollar_ble_v1_GetBatteryRequest, AUTO)


PB_BIND(onecollar_ble_v1_BatteryStatus, onecollar_ble_v1_BatteryStatus, AUTO)


PB_BIND(onecollar_ble_v1_GetGpsRequest, onecollar_ble_v1_GetGpsRequest, AUTO)


PB_BIND(onecollar_ble_v1_GpsStatus, onecollar_ble_v1_GpsStatus, AUTO)


PB_BIND(onecollar_ble_v1_GetImuSnapshotRequest, onecollar_ble_v1_GetImuSnapshotRequest, AUTO)


PB_BIND(onecollar_ble_v1_ImuSnapshot, onecollar_ble_v1_ImuSnapshot, AUTO)


PB_BIND(onecollar_ble_v1_GetSystemStatsRequest, onecollar_ble_v1_GetSystemStatsRequest, AUTO)


PB_BIND(onecollar_ble_v1_SystemStats, onecollar_ble_v1_SystemStats, AUTO)


PB_BIND(onecollar_ble_v1_GetSystemStatusRequest, onecollar_ble_v1_GetSystemStatusRequest, AUTO)


PB_BIND(onecollar_ble_v1_SystemStatus, onecollar_ble_v1_SystemStatus, AUTO)


PB_BIND(onecollar_ble_v1_GetLoraStatusRequest, onecollar_ble_v1_GetLoraStatusRequest, AUTO)


PB_BIND(onecollar_ble_v1_LoraStatus, onecollar_ble_v1_LoraStatus, AUTO)


PB_BIND(onecollar_ble_v1_GetRfStatusRequest, onecollar_ble_v1_GetRfStatusRequest, AUTO)


PB_BIND(onecollar_ble_v1_RfStatus, onecollar_ble_v1_RfStatus, AUTO)


PB_BIND(onecollar_ble_v1_GetAllRadiosRequest, onecollar_ble_v1_GetAllRadiosRequest, AUTO)


PB_BIND(onecollar_ble_v1_AllRadiosStatus, onecollar_ble_v1_AllRadiosStatus, AUTO)


PB_BIND(onecollar_ble_v1_RadioSummary, onecollar_ble_v1_RadioSummary, AUTO)


PB_BIND(onecollar_ble_v1_GetMtuStatusRequest, onecollar_ble_v1_GetMtuStatusRequest, AUTO)


PB_BIND(onecollar_ble_v1_MtuStatus, onecollar_ble_v1_MtuStatus, AUTO)


PB_BIND(onecollar_ble_v1_TimeSyncRequest, onecollar_ble_v1_TimeSyncRequest, AUTO)


PB_BIND(onecollar_ble_v1_TimeSyncResponse, onecollar_ble_v1_TimeSyncResponse, AUTO)


PB_BIND(onecollar_ble_v1_StartImuStreamRequest, onecollar_ble_v1_StartImuStreamRequest, AUTO)


PB_BIND(onecollar_ble_v1_StopImuStreamRequest, onecollar_ble_v1_StopImuStreamRequest, AUTO)


PB_BIND(onecollar_ble_v1_GetImuBatchRequest, onecollar_ble_v1_GetImuBatchRequest, AUTO)


PB_BIND(onecollar_ble_v1_GetStreamStatusRequest, onecollar_ble_v1_GetStreamStatusRequest, AUTO)


PB_BIND(onecollar_ble_v1_StreamStatus, onecollar_ble_v1_StreamStatus, AUTO)


PB_BIND(onecollar_ble_v1_ResetRequest, onecollar_ble_v1_ResetRequest, AUTO)


PB_BIND(onecollar_ble_v1_SetDebugLevelRequest, onecollar_ble_v1_SetDebugLevelRequest, AUTO)


PB_BIND(onecollar_ble_v1_SetConfigRequest, onecollar_ble_v1_SetConfigRequest, 2)


PB_BIND(onecollar_ble_v1_SetGeofenceRequest, onecollar_ble_v1_SetGeofenceRequest, 2)


PB_BIND(onecollar_ble_v1_GeofencePoint, onecollar_ble_v1_GeofencePoint, AUTO)


PB_BIND(onecollar_ble_v1_SetWallClockRequest, onecollar_ble_v1_SetWallClockRequest, AUTO)


PB_BIND(onecollar_ble_v1_StartCaptureRequest, onecollar_ble_v1_StartCaptureRequest, AUTO)


PB_BIND(onecollar_ble_v1_StartCaptureResponse, onecollar_ble_v1_StartCaptureResponse, AUTO)


PB_BIND(onecollar_ble_v1_StopCaptureRequest, onecollar_ble_v1_StopCaptureRequest, AUTO)


PB_BIND(onecollar_ble_v1_ListSessionsRequest, onecollar_ble_v1_ListSessionsRequest, AUTO)


PB_BIND(onecollar_ble_v1_SessionList, onecollar_ble_v1_SessionList, 2)


PB_BIND(onecollar_ble_v1_SessionSummary, onecollar_ble_v1_SessionSummary, AUTO)


PB_BIND(onecollar_ble_v1_ReadSessionRequest, onecollar_ble_v1_ReadSessionRequest, AUTO)


PB_BIND(onecollar_ble_v1_SessionChunk, onecollar_ble_v1_SessionChunk, 2)


PB_BIND(onecollar_ble_v1_DeleteSessionRequest, onecollar_ble_v1_DeleteSessionRequest, AUTO)


PB_BIND(onecollar_ble_v1_LabelTagRequest, onecollar_ble_v1_LabelTagRequest, AUTO)


PB_BIND(onecollar_ble_v1_BoundaryViolation, onecollar_ble_v1_BoundaryViolation, AUTO)


PB_BIND(onecollar_ble_v1_BehaviorEvent, onecollar_ble_v1_BehaviorEvent, AUTO)


PB_BIND(onecollar_ble_v1_BatteryLow, onecollar_ble_v1_BatteryLow, AUTO)


PB_BIND(onecollar_ble_v1_EchoRequest, onecollar_ble_v1_EchoRequest, 2)


PB_BIND(onecollar_ble_v1_EchoResponse, onecollar_ble_v1_EchoResponse, 2)


PB_BIND(onecollar_ble_v1_TestPatternRequest, onecollar_ble_v1_TestPatternRequest, AUTO)


PB_BIND(onecollar_ble_v1_TestPatternResponse, onecollar_ble_v1_TestPatternResponse, 2)


PB_BIND(onecollar_ble_v1_GetDebugStatsRequest, onecollar_ble_v1_GetDebugStatsRequest, AUTO)


PB_BIND(onecollar_ble_v1_DebugStats, onecollar_ble_v1_DebugStats, AUTO)















