/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ONECOLLAR_BLE_V1_BLE_PROTOCOL_PB_H_INCLUDED
#define PB_ONECOLLAR_BLE_V1_BLE_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* -----------------------------------------------------------------------------
 Status — carried on every FromCollar. STATUS_OK = success; everything else
 is an error condition. Reorder only via a v2 schema; field numbers are part
 of the wire contract.
 ----------------------------------------------------------------------------- */
typedef enum _onecollar_ble_v1_Status {
    onecollar_ble_v1_Status_STATUS_OK = 0,
    onecollar_ble_v1_Status_STATUS_INVALID_ARG = 1,
    onecollar_ble_v1_Status_STATUS_BUSY = 2,
    onecollar_ble_v1_Status_STATUS_NOT_READY = 3,
    onecollar_ble_v1_Status_STATUS_UNSUPPORTED = 4, /* feature genuinely unavailable on this hw/fw */
    onecollar_ble_v1_Status_STATUS_NOT_FOUND = 5,
    onecollar_ble_v1_Status_STATUS_STORAGE_FULL = 6,
    onecollar_ble_v1_Status_STATUS_INTERNAL = 7,
    onecollar_ble_v1_Status_STATUS_AUTHZ = 8, /* pairing / bond / permission failure */
    onecollar_ble_v1_Status_STATUS_RATE_LIMITED = 9, /* command channel spam protection */
    onecollar_ble_v1_Status_STATUS_ENTITLEMENT_REQUIRED = 10 /* feature gated by premium entitlement; pair with */
} onecollar_ble_v1_Status;

typedef enum _onecollar_ble_v1_CapabilityState {
    onecollar_ble_v1_CapabilityState_CAPABILITY_UNKNOWN = 0,
    onecollar_ble_v1_CapabilityState_CAPABILITY_AVAILABLE = 1, /* ready to use */
    onecollar_ble_v1_CapabilityState_CAPABILITY_UNAVAILABLE = 2, /* hardware/firmware does not support */
    onecollar_ble_v1_CapabilityState_CAPABILITY_AVAILABLE_WITH_UNLOCK = 3 /* gated; unlock_hint tells the app how to enable */
} onecollar_ble_v1_CapabilityState;

typedef enum _onecollar_ble_v1_ChargeState {
    onecollar_ble_v1_ChargeState_CHARGE_UNKNOWN = 0,
    onecollar_ble_v1_ChargeState_CHARGE_CHARGING = 1,
    onecollar_ble_v1_ChargeState_CHARGE_DISCHARGING = 2,
    onecollar_ble_v1_ChargeState_CHARGE_FULL = 3,
    onecollar_ble_v1_ChargeState_CHARGE_CRITICAL = 4
} onecollar_ble_v1_ChargeState;

typedef enum _onecollar_ble_v1_FixQuality {
    onecollar_ble_v1_FixQuality_FIX_INVALID = 0,
    onecollar_ble_v1_FixQuality_FIX_GPS = 1,
    onecollar_ble_v1_FixQuality_FIX_DGPS = 2,
    onecollar_ble_v1_FixQuality_FIX_PPS = 3,
    onecollar_ble_v1_FixQuality_FIX_RTK = 4,
    onecollar_ble_v1_FixQuality_FIX_FLOAT_RTK = 5
} onecollar_ble_v1_FixQuality;

typedef enum _onecollar_ble_v1_GeofenceKind {
    onecollar_ble_v1_GeofenceKind_GEOFENCE_INCLUSION = 0,
    onecollar_ble_v1_GeofenceKind_GEOFENCE_EXCLUSION = 1
} onecollar_ble_v1_GeofenceKind;

typedef enum _onecollar_ble_v1_ViolationKind {
    onecollar_ble_v1_ViolationKind_VIOLATION_EXIT = 0,
    onecollar_ble_v1_ViolationKind_VIOLATION_ENTER = 1
} onecollar_ble_v1_ViolationKind;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(480) onecollar_ble_v1_ImuBatch_samples_t;
/* ImuBatch — collar → app, on the Stream channel (stream_tx characteristic),
 unsolicited. Only message carried on this channel.

 `samples` is packed little-endian int16 in (ax, ay, az, gx, gy, gz) order,
 12 bytes per sample. NOT modelled as individual axis fields: the field-tag
 overhead would multiply the wire size by ~3x at 100 Hz.

 Sample N timestamp = base_timestamp_us + N * 1_000_000 / rate_hz.
 `seq` matches the envelope seq_id of the first fragment of this batch. */
typedef struct _onecollar_ble_v1_ImuBatch {
    uint32_t seq;
    uint64_t base_timestamp_us; /* collar clock, microseconds */
    uint32_t rate_hz;
    uint32_t sample_count;
    onecollar_ble_v1_ImuBatch_samples_t samples;
} onecollar_ble_v1_ImuBatch;

typedef struct _onecollar_ble_v1_GetCapabilitiesRequest {
    char dummy_field;
} onecollar_ble_v1_GetCapabilitiesRequest;

typedef struct _onecollar_ble_v1_Capability {
    char id[32]; /* stable lowercase-dotted id, e.g. "lora.relay" */
    onecollar_ble_v1_CapabilityState state;
    char unlock_hint[128]; /* human-readable; URL or short message; "" when not gated */
} onecollar_ble_v1_Capability;

typedef struct _onecollar_ble_v1_Capabilities {
    uint32_t schema_major;
    uint32_t schema_minor;
    uint32_t min_app_supported_major; /* app refuses to operate if its major < this */
    uint32_t hw_revision; /* 6 or 7 */
    pb_size_t capabilities_count;
    onecollar_ble_v1_Capability capabilities[32];
} onecollar_ble_v1_Capabilities;

typedef struct _onecollar_ble_v1_GetBatteryRequest {
    char dummy_field;
} onecollar_ble_v1_GetBatteryRequest;

typedef struct _onecollar_ble_v1_BatteryStatus {
    uint32_t percentage; /* 0..100 */
    uint32_t voltage_mv; /* millivolts */
    onecollar_ble_v1_ChargeState charge;
    bool alert_active;
    uint32_t alert_code; /* 0 if !alert_active; codes defined in firmware */
} onecollar_ble_v1_BatteryStatus;

typedef struct _onecollar_ble_v1_GetGpsRequest {
    char dummy_field;
} onecollar_ble_v1_GetGpsRequest;

typedef struct _onecollar_ble_v1_GpsStatus {
    bool has_fix;
    uint32_t satellites;
    onecollar_ble_v1_FixQuality fix_quality;
    uint32_t hdop_x10; /* HDOP × 10 */
    int32_t latitude_udeg; /* micro-degrees */
    int32_t longitude_udeg;
    int32_t altitude_m;
    uint64_t fix_timestamp_us; /* collar clock at fix */
} onecollar_ble_v1_GpsStatus;

typedef struct _onecollar_ble_v1_GetImuSnapshotRequest {
    char dummy_field;
} onecollar_ble_v1_GetImuSnapshotRequest;

typedef struct _onecollar_ble_v1_ImuSnapshot {
    uint64_t timestamp_us; /* collar clock */
    int32_t accel_x_mg;
    int32_t accel_y_mg;
    int32_t accel_z_mg;
    int32_t gyro_x_mdps;
    int32_t gyro_y_mdps;
    int32_t gyro_z_mdps;
} onecollar_ble_v1_ImuSnapshot;

typedef struct _onecollar_ble_v1_GetSystemStatsRequest {
    char dummy_field;
} onecollar_ble_v1_GetSystemStatsRequest;

typedef struct _onecollar_ble_v1_SystemStats {
    uint32_t cpu_pct;
    uint32_t task_count;
    uint32_t free_heap_kb;
    uint32_t min_free_heap_kb;
    uint32_t uptime_minutes;
    uint32_t error_count;
    int32_t temperature_c;
} onecollar_ble_v1_SystemStats;

typedef struct _onecollar_ble_v1_GetSystemStatusRequest {
    char dummy_field;
} onecollar_ble_v1_GetSystemStatusRequest;

typedef struct _onecollar_ble_v1_SystemStatus {
    char firmware_version[32]; /* git describe / semver */
    uint32_t hw_revision; /* 6 or 7 */
    uint64_t boot_time_us; /* collar clock at boot */
    uint32_t capability_flags; /* matches data_logger DATALOG_CAP_* bitfield */
} onecollar_ble_v1_SystemStatus;

typedef struct _onecollar_ble_v1_GetLoraStatusRequest {
    char dummy_field;
} onecollar_ble_v1_GetLoraStatusRequest;

typedef struct _onecollar_ble_v1_LoraStatus {
    bool available;
    bool active;
    int32_t rssi_dbm;
    uint32_t packets_sent;
    uint32_t packets_received;
    uint32_t frequency_hz;
    uint32_t spreading_factor;
    uint32_t bandwidth_khz;
} onecollar_ble_v1_LoraStatus;

typedef struct _onecollar_ble_v1_GetRfStatusRequest {
    char dummy_field;
} onecollar_ble_v1_GetRfStatusRequest;

typedef struct _onecollar_ble_v1_RfStatus {
    bool available;
    bool active;
    int32_t rssi_dbm;
    uint32_t frequency_hz;
    uint32_t modulation; /* 0=OOK, 1=2FSK, 2=4FSK */
    uint32_t datarate_bps;
} onecollar_ble_v1_RfStatus;

typedef struct _onecollar_ble_v1_GetAllRadiosRequest {
    char dummy_field;
} onecollar_ble_v1_GetAllRadiosRequest;

typedef struct _onecollar_ble_v1_RadioSummary {
    bool available;
    bool active;
    int32_t rssi_dbm;
} onecollar_ble_v1_RadioSummary;

typedef struct _onecollar_ble_v1_AllRadiosStatus {
    bool has_ble;
    onecollar_ble_v1_RadioSummary ble;
    bool has_lora;
    onecollar_ble_v1_RadioSummary lora;
    bool has_rf;
    onecollar_ble_v1_RadioSummary rf;
    uint32_t active_protocol; /* 0=none, 1=BLE, 2=LoRa, 3=RF */
    uint64_t total_bytes_tx;
    uint64_t total_bytes_rx;
} onecollar_ble_v1_AllRadiosStatus;

typedef struct _onecollar_ble_v1_GetMtuStatusRequest {
    char dummy_field;
} onecollar_ble_v1_GetMtuStatusRequest;

typedef struct _onecollar_ble_v1_MtuStatus {
    uint32_t negotiated_mtu;
    uint32_t max_payload_size; /* negotiated_mtu − 3 (ATT header) */
} onecollar_ble_v1_MtuStatus;

/* TimeSyncRequest / TimeSyncResponse — round-trip clock handshake.
 app sends t1 (phone Unix-epoch µs at send)
 collar timestamps t2 (collar clock at recv) and t3 (collar clock at send)
 app captures t4 (phone Unix-epoch µs at recv)
 app computes: offset = ((t2 - t1) + (t3 - t4)) / 2
              rtt    = (t4 - t1) - (t3 - t2)
 Detail in contracts/ble_protocol.md §"Time-sync handshake". */
typedef struct _onecollar_ble_v1_TimeSyncRequest {
    uint64_t phone_send_us; /* t1 */
} onecollar_ble_v1_TimeSyncRequest;

typedef struct _onecollar_ble_v1_TimeSyncResponse {
    uint64_t phone_send_us; /* t1 echo */
    uint64_t collar_recv_us; /* t2 */
    uint64_t collar_send_us; /* t3 */
} onecollar_ble_v1_TimeSyncResponse;

typedef struct _onecollar_ble_v1_StartImuStreamRequest {
    uint32_t rate_hz; /* collar clamps to a supported tier (see DECISION NEEDED #2) */
} onecollar_ble_v1_StartImuStreamRequest;

typedef struct _onecollar_ble_v1_StopImuStreamRequest {
    char dummy_field;
} onecollar_ble_v1_StopImuStreamRequest;

typedef struct _onecollar_ble_v1_GetImuBatchRequest {
    uint64_t start_timestamp_us; /* collar clock */
    uint64_t end_timestamp_us;
} onecollar_ble_v1_GetImuBatchRequest;

typedef struct _onecollar_ble_v1_GetStreamStatusRequest {
    char dummy_field;
} onecollar_ble_v1_GetStreamStatusRequest;

typedef struct _onecollar_ble_v1_StreamStatus {
    bool running;
    uint32_t rate_hz;
    uint32_t batches_sent;
    uint32_t samples_buffered;
    uint32_t buffer_capacity;
    uint32_t batches_dropped; /* back-pressure drops since stream start */
} onecollar_ble_v1_StreamStatus;

typedef struct _onecollar_ble_v1_ResetRequest {
    uint32_t delay_ms; /* collar ACKs then resets after delay_ms; 0 = immediate */
} onecollar_ble_v1_ResetRequest;

typedef struct _onecollar_ble_v1_SetDebugLevelRequest {
    uint32_t level; /* 0 = NONE .. 5 = VERBOSE */
} onecollar_ble_v1_SetDebugLevelRequest;

typedef PB_BYTES_ARRAY_T(256) onecollar_ble_v1_SetConfigRequest_value_t;
/* Generic NVS-backed key/value. Key is namespaced "config". Value semantics
 are per-key and not part of the wire schema — they live in firmware-side docs. */
typedef struct _onecollar_ble_v1_SetConfigRequest {
    char key[32];
    onecollar_ble_v1_SetConfigRequest_value_t value;
} onecollar_ble_v1_SetConfigRequest;

typedef struct _onecollar_ble_v1_GeofencePoint {
    int32_t latitude_udeg;
    int32_t longitude_udeg;
} onecollar_ble_v1_GeofencePoint;

typedef struct _onecollar_ble_v1_SetGeofenceRequest {
    uint32_t zone_id;
    char name[16];
    onecollar_ble_v1_GeofenceKind kind;
    bool enabled;
    pb_size_t points_count;
    onecollar_ble_v1_GeofencePoint points[32];
} onecollar_ble_v1_SetGeofenceRequest;

/* Absolute Unix wall-clock set. Distinct from TimeSyncRequest (which only
 establishes the collar↔phone offset). The typed RPC signals invalidation
 semantics: if the wall-clock jumps, session timestamps may need adjustment.
 Returns status only. */
typedef struct _onecollar_ble_v1_SetWallClockRequest {
    uint64_t unix_us; /* absolute Unix-epoch microseconds (UTC) */
} onecollar_ble_v1_SetWallClockRequest;

typedef struct _onecollar_ble_v1_StartCaptureRequest {
    uint32_t rate_hz; /* 0 = use default tier */
} onecollar_ble_v1_StartCaptureRequest;

typedef struct _onecollar_ble_v1_StartCaptureResponse {
    uint64_t session_id; /* collar-chosen, ms-epoch start */
    uint64_t start_time_us; /* collar clock */
} onecollar_ble_v1_StartCaptureResponse;

typedef struct _onecollar_ble_v1_StopCaptureRequest {
    char dummy_field;
} onecollar_ble_v1_StopCaptureRequest;

typedef struct _onecollar_ble_v1_ListSessionsRequest {
    char dummy_field;
} onecollar_ble_v1_ListSessionsRequest;

typedef struct _onecollar_ble_v1_SessionSummary {
    uint64_t session_id;
    uint64_t start_time_us; /* collar clock */
    uint64_t duration_us;
    uint32_t sample_count;
    uint32_t rate_hz;
    uint32_t capability_flags; /* DATALOG_CAP_* at capture time */
    uint64_t size_bytes;
} onecollar_ble_v1_SessionSummary;

typedef struct _onecollar_ble_v1_SessionList {
    pb_size_t sessions_count;
    onecollar_ble_v1_SessionSummary sessions[32];
} onecollar_ble_v1_SessionList;

/* Read a session by time range. The collar emits a series of FromCollar
 messages, each with response.session_chunk set, all sharing the request's
 envelope txn_id. `chunk_index` sequences them; `final_chunk=true` terminates
 the series. Each chunk fits in one MTU; the envelope MORE_FRAGMENTS flag is
 NOT used for this kind of chunking — that flag is reserved for messages
 that themselves exceed one MTU. */
typedef struct _onecollar_ble_v1_ReadSessionRequest {
    uint64_t session_id;
    uint64_t start_timestamp_us; /* 0 = from session start */
    uint64_t end_timestamp_us; /* 0 = to session end */
} onecollar_ble_v1_ReadSessionRequest;

typedef PB_BYTES_ARRAY_T(480) onecollar_ble_v1_SessionChunk_samples_t;
typedef struct _onecollar_ble_v1_SessionChunk {
    uint64_t session_id;
    uint32_t chunk_index;
    uint64_t first_sample_us; /* collar clock of sample 0 of this chunk */
    uint32_t rate_hz;
    uint32_t sample_count;
    onecollar_ble_v1_SessionChunk_samples_t samples; /* same packed int16 LE layout as ImuBatch.samples */
    bool final_chunk;
} onecollar_ble_v1_SessionChunk;

typedef struct _onecollar_ble_v1_DeleteSessionRequest {
    uint64_t session_id;
} onecollar_ble_v1_DeleteSessionRequest;

/* User-label injection into the active capture stream. Collar logs the label
 as DATALOG_STREAM_USER_LABEL at the collar-clock receive time. Returns
 STATUS_NOT_READY if no capture is active. Closes the firmware TODO at
 repos/OneCollarFirmwareV2/main/data_logger.h:83. */
typedef struct _onecollar_ble_v1_LabelTagRequest {
    char label[64]; /* bounded; see ble_protocol.options */
} onecollar_ble_v1_LabelTagRequest;

typedef struct _onecollar_ble_v1_BoundaryViolation {
    uint64_t timestamp_us;
    uint32_t zone_id;
    onecollar_ble_v1_ViolationKind kind;
    int32_t latitude_udeg;
    int32_t longitude_udeg;
    uint32_t distance_m;
} onecollar_ble_v1_BoundaryViolation;

typedef struct _onecollar_ble_v1_BehaviorEvent {
    uint64_t timestamp_us;
    uint32_t tree_id; /* MLC tree id, 0..7 */
    uint32_t class_id;
    uint32_t confidence; /* 0..255 */
} onecollar_ble_v1_BehaviorEvent;

typedef struct _onecollar_ble_v1_BatteryLow {
    uint32_t percentage;
    uint32_t voltage_mv;
    onecollar_ble_v1_ChargeState charge;
} onecollar_ble_v1_BatteryLow;

/* Event — collar → app, on the Events channel (event_tx characteristic),
 unsolicited. The envelope seq_id increments per event; the app detects drops
 by gaps. Reserved field numbers above 100 are for items pending decision
 (novelty, library push, training-mode) — they do not exist in v1. */
typedef struct _onecollar_ble_v1_Event {
    pb_size_t which_event;
    union {
        onecollar_ble_v1_BoundaryViolation boundary_violation;
        onecollar_ble_v1_BehaviorEvent behavior_event;
        onecollar_ble_v1_BatteryLow battery_low;
    } event;
} onecollar_ble_v1_Event;

typedef PB_BYTES_ARRAY_T(256) onecollar_ble_v1_EchoRequest_payload_t;
typedef struct _onecollar_ble_v1_EchoRequest {
    onecollar_ble_v1_EchoRequest_payload_t payload;
} onecollar_ble_v1_EchoRequest;

typedef PB_BYTES_ARRAY_T(256) onecollar_ble_v1_EchoResponse_payload_t;
typedef struct _onecollar_ble_v1_EchoResponse {
    onecollar_ble_v1_EchoResponse_payload_t payload; /* echoes EchoRequest.payload */
} onecollar_ble_v1_EchoResponse;

typedef struct _onecollar_ble_v1_TestPatternRequest {
    uint32_t pattern_id;
    uint32_t length;
} onecollar_ble_v1_TestPatternRequest;

typedef PB_BYTES_ARRAY_T(256) onecollar_ble_v1_TestPatternResponse_payload_t;
typedef struct _onecollar_ble_v1_TestPatternResponse {
    uint32_t pattern_id;
    onecollar_ble_v1_TestPatternResponse_payload_t payload;
} onecollar_ble_v1_TestPatternResponse;

typedef struct _onecollar_ble_v1_GetDebugStatsRequest {
    char dummy_field;
} onecollar_ble_v1_GetDebugStatsRequest;

/* ToCollar — app → collar, on the Command channel (cmd_rx characteristic).
 Exactly one request field is set per ToCollar. The transaction id lives in
 the envelope and is echoed in the FromCollar that responds. */
typedef struct _onecollar_ble_v1_ToCollar {
    pb_size_t which_request;
    union {
        /* Telemetry reads --------------------------------------------------------- */
        onecollar_ble_v1_GetBatteryRequest get_battery;
        onecollar_ble_v1_GetGpsRequest get_gps;
        onecollar_ble_v1_GetImuSnapshotRequest get_imu_snapshot;
        onecollar_ble_v1_GetSystemStatsRequest get_system_stats;
        onecollar_ble_v1_GetSystemStatusRequest get_system_status;
        onecollar_ble_v1_GetLoraStatusRequest get_lora_status;
        onecollar_ble_v1_GetRfStatusRequest get_rf_status;
        onecollar_ble_v1_GetAllRadiosRequest get_all_radios;
        onecollar_ble_v1_GetMtuStatusRequest get_mtu_status;
        /* Capability & version handshake ------------------------------------------ */
        onecollar_ble_v1_GetCapabilitiesRequest get_capabilities;
        /* Streaming control ------------------------------------------------------- */
        onecollar_ble_v1_TimeSyncRequest time_sync;
        onecollar_ble_v1_StartImuStreamRequest start_imu_stream;
        onecollar_ble_v1_StopImuStreamRequest stop_imu_stream;
        onecollar_ble_v1_GetImuBatchRequest get_imu_batch;
        onecollar_ble_v1_GetStreamStatusRequest get_stream_status;
        /* Control writes ---------------------------------------------------------- */
        onecollar_ble_v1_ResetRequest reset;
        onecollar_ble_v1_SetDebugLevelRequest set_debug_level;
        onecollar_ble_v1_SetConfigRequest set_config;
        onecollar_ble_v1_SetGeofenceRequest set_geofence;
        onecollar_ble_v1_SetWallClockRequest set_wall_clock;
        /* Session capture --------------------------------------------------------- */
        onecollar_ble_v1_StartCaptureRequest start_capture;
        onecollar_ble_v1_StopCaptureRequest stop_capture;
        onecollar_ble_v1_ListSessionsRequest list_sessions;
        onecollar_ble_v1_ReadSessionRequest read_session;
        onecollar_ble_v1_DeleteSessionRequest delete_session;
        onecollar_ble_v1_LabelTagRequest label_tag;
        /* Debug ------------------------------------------------------------------- */
        onecollar_ble_v1_EchoRequest echo;
        onecollar_ble_v1_TestPatternRequest test_pattern;
        onecollar_ble_v1_GetDebugStatsRequest get_debug_stats;
    } request;
} onecollar_ble_v1_ToCollar;

typedef struct _onecollar_ble_v1_DebugStats {
    uint64_t commands_received;
    uint64_t responses_sent;
    uint64_t events_sent;
    uint64_t bytes_received;
    uint64_t bytes_sent;
    uint64_t frame_errors; /* length / type mismatches */
    uint64_t crc_errors;
} onecollar_ble_v1_DebugStats;

/* FromCollar — collar → app, on the Command channel (cmd_tx characteristic).
 `status` is always set. If status != STATUS_OK the response payload MAY be
 omitted. Requests that do not return a payload (reset, set_*, stop_*) reply
 with FromCollar{ status: ... } and no oneof variant set. */
typedef struct _onecollar_ble_v1_FromCollar {
    onecollar_ble_v1_Status status;
    pb_size_t which_response;
    union {
        onecollar_ble_v1_BatteryStatus battery;
        onecollar_ble_v1_GpsStatus gps;
        onecollar_ble_v1_ImuSnapshot imu_snapshot;
        onecollar_ble_v1_SystemStats system_stats;
        onecollar_ble_v1_SystemStatus system_status;
        onecollar_ble_v1_LoraStatus lora_status;
        onecollar_ble_v1_RfStatus rf_status;
        onecollar_ble_v1_AllRadiosStatus all_radios;
        onecollar_ble_v1_MtuStatus mtu_status;
        onecollar_ble_v1_Capabilities capabilities;
        onecollar_ble_v1_TimeSyncResponse time_sync;
        onecollar_ble_v1_StreamStatus stream_status; /* start_imu_stream / stop_imu_stream return status only.
     get_imu_batch results are delivered on the Stream channel as ImuBatch. */
        onecollar_ble_v1_StartCaptureResponse start_capture;
        onecollar_ble_v1_SessionList session_list;
        onecollar_ble_v1_SessionChunk session_chunk; /* see envelope rules below */
        onecollar_ble_v1_EchoResponse echo;
        onecollar_ble_v1_TestPatternResponse test_pattern;
        onecollar_ble_v1_DebugStats debug_stats;
    } response;
} onecollar_ble_v1_FromCollar;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _onecollar_ble_v1_Status_MIN onecollar_ble_v1_Status_STATUS_OK
#define _onecollar_ble_v1_Status_MAX onecollar_ble_v1_Status_STATUS_ENTITLEMENT_REQUIRED
#define _onecollar_ble_v1_Status_ARRAYSIZE ((onecollar_ble_v1_Status)(onecollar_ble_v1_Status_STATUS_ENTITLEMENT_REQUIRED+1))

#define _onecollar_ble_v1_CapabilityState_MIN onecollar_ble_v1_CapabilityState_CAPABILITY_UNKNOWN
#define _onecollar_ble_v1_CapabilityState_MAX onecollar_ble_v1_CapabilityState_CAPABILITY_AVAILABLE_WITH_UNLOCK
#define _onecollar_ble_v1_CapabilityState_ARRAYSIZE ((onecollar_ble_v1_CapabilityState)(onecollar_ble_v1_CapabilityState_CAPABILITY_AVAILABLE_WITH_UNLOCK+1))

#define _onecollar_ble_v1_ChargeState_MIN onecollar_ble_v1_ChargeState_CHARGE_UNKNOWN
#define _onecollar_ble_v1_ChargeState_MAX onecollar_ble_v1_ChargeState_CHARGE_CRITICAL
#define _onecollar_ble_v1_ChargeState_ARRAYSIZE ((onecollar_ble_v1_ChargeState)(onecollar_ble_v1_ChargeState_CHARGE_CRITICAL+1))

#define _onecollar_ble_v1_FixQuality_MIN onecollar_ble_v1_FixQuality_FIX_INVALID
#define _onecollar_ble_v1_FixQuality_MAX onecollar_ble_v1_FixQuality_FIX_FLOAT_RTK
#define _onecollar_ble_v1_FixQuality_ARRAYSIZE ((onecollar_ble_v1_FixQuality)(onecollar_ble_v1_FixQuality_FIX_FLOAT_RTK+1))

#define _onecollar_ble_v1_GeofenceKind_MIN onecollar_ble_v1_GeofenceKind_GEOFENCE_INCLUSION
#define _onecollar_ble_v1_GeofenceKind_MAX onecollar_ble_v1_GeofenceKind_GEOFENCE_EXCLUSION
#define _onecollar_ble_v1_GeofenceKind_ARRAYSIZE ((onecollar_ble_v1_GeofenceKind)(onecollar_ble_v1_GeofenceKind_GEOFENCE_EXCLUSION+1))

#define _onecollar_ble_v1_ViolationKind_MIN onecollar_ble_v1_ViolationKind_VIOLATION_EXIT
#define _onecollar_ble_v1_ViolationKind_MAX onecollar_ble_v1_ViolationKind_VIOLATION_ENTER
#define _onecollar_ble_v1_ViolationKind_ARRAYSIZE ((onecollar_ble_v1_ViolationKind)(onecollar_ble_v1_ViolationKind_VIOLATION_ENTER+1))


#define onecollar_ble_v1_FromCollar_status_ENUMTYPE onecollar_ble_v1_Status





#define onecollar_ble_v1_Capability_state_ENUMTYPE onecollar_ble_v1_CapabilityState


#define onecollar_ble_v1_BatteryStatus_charge_ENUMTYPE onecollar_ble_v1_ChargeState


#define onecollar_ble_v1_GpsStatus_fix_quality_ENUMTYPE onecollar_ble_v1_FixQuality


























#define onecollar_ble_v1_SetGeofenceRequest_kind_ENUMTYPE onecollar_ble_v1_GeofenceKind













#define onecollar_ble_v1_BoundaryViolation_kind_ENUMTYPE onecollar_ble_v1_ViolationKind


#define onecollar_ble_v1_BatteryLow_charge_ENUMTYPE onecollar_ble_v1_ChargeState








/* Initializer values for message structs */
#define onecollar_ble_v1_ToCollar_init_default   {0, {onecollar_ble_v1_GetBatteryRequest_init_default}}
#define onecollar_ble_v1_FromCollar_init_default {_onecollar_ble_v1_Status_MIN, 0, {onecollar_ble_v1_BatteryStatus_init_default}}
#define onecollar_ble_v1_Event_init_default      {0, {onecollar_ble_v1_BoundaryViolation_init_default}}
#define onecollar_ble_v1_ImuBatch_init_default   {0, 0, 0, 0, {0, {0}}}
#define onecollar_ble_v1_GetCapabilitiesRequest_init_default {0}
#define onecollar_ble_v1_Capabilities_init_default {0, 0, 0, 0, 0, {onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default, onecollar_ble_v1_Capability_init_default}}
#define onecollar_ble_v1_Capability_init_default {"", _onecollar_ble_v1_CapabilityState_MIN, ""}
#define onecollar_ble_v1_GetBatteryRequest_init_default {0}
#define onecollar_ble_v1_BatteryStatus_init_default {0, 0, _onecollar_ble_v1_ChargeState_MIN, 0, 0}
#define onecollar_ble_v1_GetGpsRequest_init_default {0}
#define onecollar_ble_v1_GpsStatus_init_default  {0, 0, _onecollar_ble_v1_FixQuality_MIN, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetImuSnapshotRequest_init_default {0}
#define onecollar_ble_v1_ImuSnapshot_init_default {0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetSystemStatsRequest_init_default {0}
#define onecollar_ble_v1_SystemStats_init_default {0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetSystemStatusRequest_init_default {0}
#define onecollar_ble_v1_SystemStatus_init_default {"", 0, 0, 0}
#define onecollar_ble_v1_GetLoraStatusRequest_init_default {0}
#define onecollar_ble_v1_LoraStatus_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetRfStatusRequest_init_default {0}
#define onecollar_ble_v1_RfStatus_init_default   {0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetAllRadiosRequest_init_default {0}
#define onecollar_ble_v1_AllRadiosStatus_init_default {false, onecollar_ble_v1_RadioSummary_init_default, false, onecollar_ble_v1_RadioSummary_init_default, false, onecollar_ble_v1_RadioSummary_init_default, 0, 0, 0}
#define onecollar_ble_v1_RadioSummary_init_default {0, 0, 0}
#define onecollar_ble_v1_GetMtuStatusRequest_init_default {0}
#define onecollar_ble_v1_MtuStatus_init_default  {0, 0}
#define onecollar_ble_v1_TimeSyncRequest_init_default {0}
#define onecollar_ble_v1_TimeSyncResponse_init_default {0, 0, 0}
#define onecollar_ble_v1_StartImuStreamRequest_init_default {0}
#define onecollar_ble_v1_StopImuStreamRequest_init_default {0}
#define onecollar_ble_v1_GetImuBatchRequest_init_default {0, 0}
#define onecollar_ble_v1_GetStreamStatusRequest_init_default {0}
#define onecollar_ble_v1_StreamStatus_init_default {0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_ResetRequest_init_default {0}
#define onecollar_ble_v1_SetDebugLevelRequest_init_default {0}
#define onecollar_ble_v1_SetConfigRequest_init_default {"", {0, {0}}}
#define onecollar_ble_v1_SetGeofenceRequest_init_default {0, "", _onecollar_ble_v1_GeofenceKind_MIN, 0, 0, {onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default, onecollar_ble_v1_GeofencePoint_init_default}}
#define onecollar_ble_v1_GeofencePoint_init_default {0, 0}
#define onecollar_ble_v1_SetWallClockRequest_init_default {0}
#define onecollar_ble_v1_StartCaptureRequest_init_default {0}
#define onecollar_ble_v1_StartCaptureResponse_init_default {0, 0}
#define onecollar_ble_v1_StopCaptureRequest_init_default {0}
#define onecollar_ble_v1_ListSessionsRequest_init_default {0}
#define onecollar_ble_v1_SessionList_init_default {0, {onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default, onecollar_ble_v1_SessionSummary_init_default}}
#define onecollar_ble_v1_SessionSummary_init_default {0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_ReadSessionRequest_init_default {0, 0, 0}
#define onecollar_ble_v1_SessionChunk_init_default {0, 0, 0, 0, 0, {0, {0}}, 0}
#define onecollar_ble_v1_DeleteSessionRequest_init_default {0}
#define onecollar_ble_v1_LabelTagRequest_init_default {""}
#define onecollar_ble_v1_BoundaryViolation_init_default {0, 0, _onecollar_ble_v1_ViolationKind_MIN, 0, 0, 0}
#define onecollar_ble_v1_BehaviorEvent_init_default {0, 0, 0, 0}
#define onecollar_ble_v1_BatteryLow_init_default {0, 0, _onecollar_ble_v1_ChargeState_MIN}
#define onecollar_ble_v1_EchoRequest_init_default {{0, {0}}}
#define onecollar_ble_v1_EchoResponse_init_default {{0, {0}}}
#define onecollar_ble_v1_TestPatternRequest_init_default {0, 0}
#define onecollar_ble_v1_TestPatternResponse_init_default {0, {0, {0}}}
#define onecollar_ble_v1_GetDebugStatsRequest_init_default {0}
#define onecollar_ble_v1_DebugStats_init_default {0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_ToCollar_init_zero      {0, {onecollar_ble_v1_GetBatteryRequest_init_zero}}
#define onecollar_ble_v1_FromCollar_init_zero    {_onecollar_ble_v1_Status_MIN, 0, {onecollar_ble_v1_BatteryStatus_init_zero}}
#define onecollar_ble_v1_Event_init_zero         {0, {onecollar_ble_v1_BoundaryViolation_init_zero}}
#define onecollar_ble_v1_ImuBatch_init_zero      {0, 0, 0, 0, {0, {0}}}
#define onecollar_ble_v1_GetCapabilitiesRequest_init_zero {0}
#define onecollar_ble_v1_Capabilities_init_zero  {0, 0, 0, 0, 0, {onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero, onecollar_ble_v1_Capability_init_zero}}
#define onecollar_ble_v1_Capability_init_zero    {"", _onecollar_ble_v1_CapabilityState_MIN, ""}
#define onecollar_ble_v1_GetBatteryRequest_init_zero {0}
#define onecollar_ble_v1_BatteryStatus_init_zero {0, 0, _onecollar_ble_v1_ChargeState_MIN, 0, 0}
#define onecollar_ble_v1_GetGpsRequest_init_zero {0}
#define onecollar_ble_v1_GpsStatus_init_zero     {0, 0, _onecollar_ble_v1_FixQuality_MIN, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetImuSnapshotRequest_init_zero {0}
#define onecollar_ble_v1_ImuSnapshot_init_zero   {0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetSystemStatsRequest_init_zero {0}
#define onecollar_ble_v1_SystemStats_init_zero   {0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetSystemStatusRequest_init_zero {0}
#define onecollar_ble_v1_SystemStatus_init_zero  {"", 0, 0, 0}
#define onecollar_ble_v1_GetLoraStatusRequest_init_zero {0}
#define onecollar_ble_v1_LoraStatus_init_zero    {0, 0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetRfStatusRequest_init_zero {0}
#define onecollar_ble_v1_RfStatus_init_zero      {0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_GetAllRadiosRequest_init_zero {0}
#define onecollar_ble_v1_AllRadiosStatus_init_zero {false, onecollar_ble_v1_RadioSummary_init_zero, false, onecollar_ble_v1_RadioSummary_init_zero, false, onecollar_ble_v1_RadioSummary_init_zero, 0, 0, 0}
#define onecollar_ble_v1_RadioSummary_init_zero  {0, 0, 0}
#define onecollar_ble_v1_GetMtuStatusRequest_init_zero {0}
#define onecollar_ble_v1_MtuStatus_init_zero     {0, 0}
#define onecollar_ble_v1_TimeSyncRequest_init_zero {0}
#define onecollar_ble_v1_TimeSyncResponse_init_zero {0, 0, 0}
#define onecollar_ble_v1_StartImuStreamRequest_init_zero {0}
#define onecollar_ble_v1_StopImuStreamRequest_init_zero {0}
#define onecollar_ble_v1_GetImuBatchRequest_init_zero {0, 0}
#define onecollar_ble_v1_GetStreamStatusRequest_init_zero {0}
#define onecollar_ble_v1_StreamStatus_init_zero  {0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_ResetRequest_init_zero  {0}
#define onecollar_ble_v1_SetDebugLevelRequest_init_zero {0}
#define onecollar_ble_v1_SetConfigRequest_init_zero {"", {0, {0}}}
#define onecollar_ble_v1_SetGeofenceRequest_init_zero {0, "", _onecollar_ble_v1_GeofenceKind_MIN, 0, 0, {onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero, onecollar_ble_v1_GeofencePoint_init_zero}}
#define onecollar_ble_v1_GeofencePoint_init_zero {0, 0}
#define onecollar_ble_v1_SetWallClockRequest_init_zero {0}
#define onecollar_ble_v1_StartCaptureRequest_init_zero {0}
#define onecollar_ble_v1_StartCaptureResponse_init_zero {0, 0}
#define onecollar_ble_v1_StopCaptureRequest_init_zero {0}
#define onecollar_ble_v1_ListSessionsRequest_init_zero {0}
#define onecollar_ble_v1_SessionList_init_zero   {0, {onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero, onecollar_ble_v1_SessionSummary_init_zero}}
#define onecollar_ble_v1_SessionSummary_init_zero {0, 0, 0, 0, 0, 0, 0}
#define onecollar_ble_v1_ReadSessionRequest_init_zero {0, 0, 0}
#define onecollar_ble_v1_SessionChunk_init_zero  {0, 0, 0, 0, 0, {0, {0}}, 0}
#define onecollar_ble_v1_DeleteSessionRequest_init_zero {0}
#define onecollar_ble_v1_LabelTagRequest_init_zero {""}
#define onecollar_ble_v1_BoundaryViolation_init_zero {0, 0, _onecollar_ble_v1_ViolationKind_MIN, 0, 0, 0}
#define onecollar_ble_v1_BehaviorEvent_init_zero {0, 0, 0, 0}
#define onecollar_ble_v1_BatteryLow_init_zero    {0, 0, _onecollar_ble_v1_ChargeState_MIN}
#define onecollar_ble_v1_EchoRequest_init_zero   {{0, {0}}}
#define onecollar_ble_v1_EchoResponse_init_zero  {{0, {0}}}
#define onecollar_ble_v1_TestPatternRequest_init_zero {0, 0}
#define onecollar_ble_v1_TestPatternResponse_init_zero {0, {0, {0}}}
#define onecollar_ble_v1_GetDebugStatsRequest_init_zero {0}
#define onecollar_ble_v1_DebugStats_init_zero    {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define onecollar_ble_v1_ImuBatch_seq_tag        1
#define onecollar_ble_v1_ImuBatch_base_timestamp_us_tag 2
#define onecollar_ble_v1_ImuBatch_rate_hz_tag    3
#define onecollar_ble_v1_ImuBatch_sample_count_tag 4
#define onecollar_ble_v1_ImuBatch_samples_tag    5
#define onecollar_ble_v1_Capability_id_tag       1
#define onecollar_ble_v1_Capability_state_tag    2
#define onecollar_ble_v1_Capability_unlock_hint_tag 3
#define onecollar_ble_v1_Capabilities_schema_major_tag 1
#define onecollar_ble_v1_Capabilities_schema_minor_tag 2
#define onecollar_ble_v1_Capabilities_min_app_supported_major_tag 3
#define onecollar_ble_v1_Capabilities_hw_revision_tag 4
#define onecollar_ble_v1_Capabilities_capabilities_tag 5
#define onecollar_ble_v1_BatteryStatus_percentage_tag 1
#define onecollar_ble_v1_BatteryStatus_voltage_mv_tag 2
#define onecollar_ble_v1_BatteryStatus_charge_tag 3
#define onecollar_ble_v1_BatteryStatus_alert_active_tag 4
#define onecollar_ble_v1_BatteryStatus_alert_code_tag 5
#define onecollar_ble_v1_GpsStatus_has_fix_tag   1
#define onecollar_ble_v1_GpsStatus_satellites_tag 2
#define onecollar_ble_v1_GpsStatus_fix_quality_tag 3
#define onecollar_ble_v1_GpsStatus_hdop_x10_tag  4
#define onecollar_ble_v1_GpsStatus_latitude_udeg_tag 5
#define onecollar_ble_v1_GpsStatus_longitude_udeg_tag 6
#define onecollar_ble_v1_GpsStatus_altitude_m_tag 7
#define onecollar_ble_v1_GpsStatus_fix_timestamp_us_tag 8
#define onecollar_ble_v1_ImuSnapshot_timestamp_us_tag 1
#define onecollar_ble_v1_ImuSnapshot_accel_x_mg_tag 2
#define onecollar_ble_v1_ImuSnapshot_accel_y_mg_tag 3
#define onecollar_ble_v1_ImuSnapshot_accel_z_mg_tag 4
#define onecollar_ble_v1_ImuSnapshot_gyro_x_mdps_tag 5
#define onecollar_ble_v1_ImuSnapshot_gyro_y_mdps_tag 6
#define onecollar_ble_v1_ImuSnapshot_gyro_z_mdps_tag 7
#define onecollar_ble_v1_SystemStats_cpu_pct_tag 1
#define onecollar_ble_v1_SystemStats_task_count_tag 2
#define onecollar_ble_v1_SystemStats_free_heap_kb_tag 3
#define onecollar_ble_v1_SystemStats_min_free_heap_kb_tag 4
#define onecollar_ble_v1_SystemStats_uptime_minutes_tag 5
#define onecollar_ble_v1_SystemStats_error_count_tag 6
#define onecollar_ble_v1_SystemStats_temperature_c_tag 7
#define onecollar_ble_v1_SystemStatus_firmware_version_tag 1
#define onecollar_ble_v1_SystemStatus_hw_revision_tag 2
#define onecollar_ble_v1_SystemStatus_boot_time_us_tag 3
#define onecollar_ble_v1_SystemStatus_capability_flags_tag 4
#define onecollar_ble_v1_LoraStatus_available_tag 1
#define onecollar_ble_v1_LoraStatus_active_tag   2
#define onecollar_ble_v1_LoraStatus_rssi_dbm_tag 3
#define onecollar_ble_v1_LoraStatus_packets_sent_tag 4
#define onecollar_ble_v1_LoraStatus_packets_received_tag 5
#define onecollar_ble_v1_LoraStatus_frequency_hz_tag 6
#define onecollar_ble_v1_LoraStatus_spreading_factor_tag 7
#define onecollar_ble_v1_LoraStatus_bandwidth_khz_tag 8
#define onecollar_ble_v1_RfStatus_available_tag  1
#define onecollar_ble_v1_RfStatus_active_tag     2
#define onecollar_ble_v1_RfStatus_rssi_dbm_tag   3
#define onecollar_ble_v1_RfStatus_frequency_hz_tag 4
#define onecollar_ble_v1_RfStatus_modulation_tag 5
#define onecollar_ble_v1_RfStatus_datarate_bps_tag 6
#define onecollar_ble_v1_RadioSummary_available_tag 1
#define onecollar_ble_v1_RadioSummary_active_tag 2
#define onecollar_ble_v1_RadioSummary_rssi_dbm_tag 3
#define onecollar_ble_v1_AllRadiosStatus_ble_tag 1
#define onecollar_ble_v1_AllRadiosStatus_lora_tag 2
#define onecollar_ble_v1_AllRadiosStatus_rf_tag  3
#define onecollar_ble_v1_AllRadiosStatus_active_protocol_tag 4
#define onecollar_ble_v1_AllRadiosStatus_total_bytes_tx_tag 5
#define onecollar_ble_v1_AllRadiosStatus_total_bytes_rx_tag 6
#define onecollar_ble_v1_MtuStatus_negotiated_mtu_tag 1
#define onecollar_ble_v1_MtuStatus_max_payload_size_tag 2
#define onecollar_ble_v1_TimeSyncRequest_phone_send_us_tag 1
#define onecollar_ble_v1_TimeSyncResponse_phone_send_us_tag 1
#define onecollar_ble_v1_TimeSyncResponse_collar_recv_us_tag 2
#define onecollar_ble_v1_TimeSyncResponse_collar_send_us_tag 3
#define onecollar_ble_v1_StartImuStreamRequest_rate_hz_tag 1
#define onecollar_ble_v1_GetImuBatchRequest_start_timestamp_us_tag 1
#define onecollar_ble_v1_GetImuBatchRequest_end_timestamp_us_tag 2
#define onecollar_ble_v1_StreamStatus_running_tag 1
#define onecollar_ble_v1_StreamStatus_rate_hz_tag 2
#define onecollar_ble_v1_StreamStatus_batches_sent_tag 3
#define onecollar_ble_v1_StreamStatus_samples_buffered_tag 4
#define onecollar_ble_v1_StreamStatus_buffer_capacity_tag 5
#define onecollar_ble_v1_StreamStatus_batches_dropped_tag 6
#define onecollar_ble_v1_ResetRequest_delay_ms_tag 1
#define onecollar_ble_v1_SetDebugLevelRequest_level_tag 1
#define onecollar_ble_v1_SetConfigRequest_key_tag 1
#define onecollar_ble_v1_SetConfigRequest_value_tag 2
#define onecollar_ble_v1_GeofencePoint_latitude_udeg_tag 1
#define onecollar_ble_v1_GeofencePoint_longitude_udeg_tag 2
#define onecollar_ble_v1_SetGeofenceRequest_zone_id_tag 1
#define onecollar_ble_v1_SetGeofenceRequest_name_tag 2
#define onecollar_ble_v1_SetGeofenceRequest_kind_tag 3
#define onecollar_ble_v1_SetGeofenceRequest_enabled_tag 4
#define onecollar_ble_v1_SetGeofenceRequest_points_tag 5
#define onecollar_ble_v1_SetWallClockRequest_unix_us_tag 1
#define onecollar_ble_v1_StartCaptureRequest_rate_hz_tag 1
#define onecollar_ble_v1_StartCaptureResponse_session_id_tag 1
#define onecollar_ble_v1_StartCaptureResponse_start_time_us_tag 2
#define onecollar_ble_v1_SessionSummary_session_id_tag 1
#define onecollar_ble_v1_SessionSummary_start_time_us_tag 2
#define onecollar_ble_v1_SessionSummary_duration_us_tag 3
#define onecollar_ble_v1_SessionSummary_sample_count_tag 4
#define onecollar_ble_v1_SessionSummary_rate_hz_tag 5
#define onecollar_ble_v1_SessionSummary_capability_flags_tag 6
#define onecollar_ble_v1_SessionSummary_size_bytes_tag 7
#define onecollar_ble_v1_SessionList_sessions_tag 1
#define onecollar_ble_v1_ReadSessionRequest_session_id_tag 1
#define onecollar_ble_v1_ReadSessionRequest_start_timestamp_us_tag 2
#define onecollar_ble_v1_ReadSessionRequest_end_timestamp_us_tag 3
#define onecollar_ble_v1_SessionChunk_session_id_tag 1
#define onecollar_ble_v1_SessionChunk_chunk_index_tag 2
#define onecollar_ble_v1_SessionChunk_first_sample_us_tag 3
#define onecollar_ble_v1_SessionChunk_rate_hz_tag 4
#define onecollar_ble_v1_SessionChunk_sample_count_tag 5
#define onecollar_ble_v1_SessionChunk_samples_tag 6
#define onecollar_ble_v1_SessionChunk_final_chunk_tag 7
#define onecollar_ble_v1_DeleteSessionRequest_session_id_tag 1
#define onecollar_ble_v1_LabelTagRequest_label_tag 1
#define onecollar_ble_v1_BoundaryViolation_timestamp_us_tag 1
#define onecollar_ble_v1_BoundaryViolation_zone_id_tag 2
#define onecollar_ble_v1_BoundaryViolation_kind_tag 3
#define onecollar_ble_v1_BoundaryViolation_latitude_udeg_tag 4
#define onecollar_ble_v1_BoundaryViolation_longitude_udeg_tag 5
#define onecollar_ble_v1_BoundaryViolation_distance_m_tag 6
#define onecollar_ble_v1_BehaviorEvent_timestamp_us_tag 1
#define onecollar_ble_v1_BehaviorEvent_tree_id_tag 2
#define onecollar_ble_v1_BehaviorEvent_class_id_tag 3
#define onecollar_ble_v1_BehaviorEvent_confidence_tag 4
#define onecollar_ble_v1_BatteryLow_percentage_tag 1
#define onecollar_ble_v1_BatteryLow_voltage_mv_tag 2
#define onecollar_ble_v1_BatteryLow_charge_tag   3
#define onecollar_ble_v1_Event_boundary_violation_tag 1
#define onecollar_ble_v1_Event_behavior_event_tag 2
#define onecollar_ble_v1_Event_battery_low_tag   3
#define onecollar_ble_v1_EchoRequest_payload_tag 1
#define onecollar_ble_v1_EchoResponse_payload_tag 1
#define onecollar_ble_v1_TestPatternRequest_pattern_id_tag 1
#define onecollar_ble_v1_TestPatternRequest_length_tag 2
#define onecollar_ble_v1_TestPatternResponse_pattern_id_tag 1
#define onecollar_ble_v1_TestPatternResponse_payload_tag 2
#define onecollar_ble_v1_ToCollar_get_battery_tag 1
#define onecollar_ble_v1_ToCollar_get_gps_tag    2
#define onecollar_ble_v1_ToCollar_get_imu_snapshot_tag 3
#define onecollar_ble_v1_ToCollar_get_system_stats_tag 4
#define onecollar_ble_v1_ToCollar_get_system_status_tag 5
#define onecollar_ble_v1_ToCollar_get_lora_status_tag 6
#define onecollar_ble_v1_ToCollar_get_rf_status_tag 7
#define onecollar_ble_v1_ToCollar_get_all_radios_tag 8
#define onecollar_ble_v1_ToCollar_get_mtu_status_tag 9
#define onecollar_ble_v1_ToCollar_get_capabilities_tag 10
#define onecollar_ble_v1_ToCollar_time_sync_tag  20
#define onecollar_ble_v1_ToCollar_start_imu_stream_tag 21
#define onecollar_ble_v1_ToCollar_stop_imu_stream_tag 22
#define onecollar_ble_v1_ToCollar_get_imu_batch_tag 23
#define onecollar_ble_v1_ToCollar_get_stream_status_tag 24
#define onecollar_ble_v1_ToCollar_reset_tag      40
#define onecollar_ble_v1_ToCollar_set_debug_level_tag 41
#define onecollar_ble_v1_ToCollar_set_config_tag 42
#define onecollar_ble_v1_ToCollar_set_geofence_tag 43
#define onecollar_ble_v1_ToCollar_set_wall_clock_tag 44
#define onecollar_ble_v1_ToCollar_start_capture_tag 60
#define onecollar_ble_v1_ToCollar_stop_capture_tag 61
#define onecollar_ble_v1_ToCollar_list_sessions_tag 62
#define onecollar_ble_v1_ToCollar_read_session_tag 63
#define onecollar_ble_v1_ToCollar_delete_session_tag 64
#define onecollar_ble_v1_ToCollar_label_tag_tag  65
#define onecollar_ble_v1_ToCollar_echo_tag       240
#define onecollar_ble_v1_ToCollar_test_pattern_tag 241
#define onecollar_ble_v1_ToCollar_get_debug_stats_tag 242
#define onecollar_ble_v1_DebugStats_commands_received_tag 1
#define onecollar_ble_v1_DebugStats_responses_sent_tag 2
#define onecollar_ble_v1_DebugStats_events_sent_tag 3
#define onecollar_ble_v1_DebugStats_bytes_received_tag 4
#define onecollar_ble_v1_DebugStats_bytes_sent_tag 5
#define onecollar_ble_v1_DebugStats_frame_errors_tag 6
#define onecollar_ble_v1_DebugStats_crc_errors_tag 7
#define onecollar_ble_v1_FromCollar_status_tag   1
#define onecollar_ble_v1_FromCollar_battery_tag  10
#define onecollar_ble_v1_FromCollar_gps_tag      11
#define onecollar_ble_v1_FromCollar_imu_snapshot_tag 12
#define onecollar_ble_v1_FromCollar_system_stats_tag 13
#define onecollar_ble_v1_FromCollar_system_status_tag 14
#define onecollar_ble_v1_FromCollar_lora_status_tag 15
#define onecollar_ble_v1_FromCollar_rf_status_tag 16
#define onecollar_ble_v1_FromCollar_all_radios_tag 17
#define onecollar_ble_v1_FromCollar_mtu_status_tag 18
#define onecollar_ble_v1_FromCollar_capabilities_tag 19
#define onecollar_ble_v1_FromCollar_time_sync_tag 30
#define onecollar_ble_v1_FromCollar_stream_status_tag 31
#define onecollar_ble_v1_FromCollar_start_capture_tag 70
#define onecollar_ble_v1_FromCollar_session_list_tag 71
#define onecollar_ble_v1_FromCollar_session_chunk_tag 72
#define onecollar_ble_v1_FromCollar_echo_tag     250
#define onecollar_ble_v1_FromCollar_test_pattern_tag 251
#define onecollar_ble_v1_FromCollar_debug_stats_tag 252

/* Struct field encoding specification for nanopb */
#define onecollar_ble_v1_ToCollar_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_battery,request.get_battery),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_gps,request.get_gps),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_imu_snapshot,request.get_imu_snapshot),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_system_stats,request.get_system_stats),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_system_status,request.get_system_status),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_lora_status,request.get_lora_status),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_rf_status,request.get_rf_status),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_all_radios,request.get_all_radios),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_mtu_status,request.get_mtu_status),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_capabilities,request.get_capabilities),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,time_sync,request.time_sync),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,start_imu_stream,request.start_imu_stream),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,stop_imu_stream,request.stop_imu_stream),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_imu_batch,request.get_imu_batch),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_stream_status,request.get_stream_status),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,reset,request.reset),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_debug_level,request.set_debug_level),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_config,request.set_config),  42) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_geofence,request.set_geofence),  43) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_wall_clock,request.set_wall_clock),  44) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,start_capture,request.start_capture),  60) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,stop_capture,request.stop_capture),  61) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,list_sessions,request.list_sessions),  62) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,read_session,request.read_session),  63) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,delete_session,request.delete_session),  64) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,label_tag,request.label_tag),  65) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,echo,request.echo), 240) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,test_pattern,request.test_pattern), 241) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_debug_stats,request.get_debug_stats), 242)
#define onecollar_ble_v1_ToCollar_CALLBACK NULL
#define onecollar_ble_v1_ToCollar_DEFAULT NULL
#define onecollar_ble_v1_ToCollar_request_get_battery_MSGTYPE onecollar_ble_v1_GetBatteryRequest
#define onecollar_ble_v1_ToCollar_request_get_gps_MSGTYPE onecollar_ble_v1_GetGpsRequest
#define onecollar_ble_v1_ToCollar_request_get_imu_snapshot_MSGTYPE onecollar_ble_v1_GetImuSnapshotRequest
#define onecollar_ble_v1_ToCollar_request_get_system_stats_MSGTYPE onecollar_ble_v1_GetSystemStatsRequest
#define onecollar_ble_v1_ToCollar_request_get_system_status_MSGTYPE onecollar_ble_v1_GetSystemStatusRequest
#define onecollar_ble_v1_ToCollar_request_get_lora_status_MSGTYPE onecollar_ble_v1_GetLoraStatusRequest
#define onecollar_ble_v1_ToCollar_request_get_rf_status_MSGTYPE onecollar_ble_v1_GetRfStatusRequest
#define onecollar_ble_v1_ToCollar_request_get_all_radios_MSGTYPE onecollar_ble_v1_GetAllRadiosRequest
#define onecollar_ble_v1_ToCollar_request_get_mtu_status_MSGTYPE onecollar_ble_v1_GetMtuStatusRequest
#define onecollar_ble_v1_ToCollar_request_get_capabilities_MSGTYPE onecollar_ble_v1_GetCapabilitiesRequest
#define onecollar_ble_v1_ToCollar_request_time_sync_MSGTYPE onecollar_ble_v1_TimeSyncRequest
#define onecollar_ble_v1_ToCollar_request_start_imu_stream_MSGTYPE onecollar_ble_v1_StartImuStreamRequest
#define onecollar_ble_v1_ToCollar_request_stop_imu_stream_MSGTYPE onecollar_ble_v1_StopImuStreamRequest
#define onecollar_ble_v1_ToCollar_request_get_imu_batch_MSGTYPE onecollar_ble_v1_GetImuBatchRequest
#define onecollar_ble_v1_ToCollar_request_get_stream_status_MSGTYPE onecollar_ble_v1_GetStreamStatusRequest
#define onecollar_ble_v1_ToCollar_request_reset_MSGTYPE onecollar_ble_v1_ResetRequest
#define onecollar_ble_v1_ToCollar_request_set_debug_level_MSGTYPE onecollar_ble_v1_SetDebugLevelRequest
#define onecollar_ble_v1_ToCollar_request_set_config_MSGTYPE onecollar_ble_v1_SetConfigRequest
#define onecollar_ble_v1_ToCollar_request_set_geofence_MSGTYPE onecollar_ble_v1_SetGeofenceRequest
#define onecollar_ble_v1_ToCollar_request_set_wall_clock_MSGTYPE onecollar_ble_v1_SetWallClockRequest
#define onecollar_ble_v1_ToCollar_request_start_capture_MSGTYPE onecollar_ble_v1_StartCaptureRequest
#define onecollar_ble_v1_ToCollar_request_stop_capture_MSGTYPE onecollar_ble_v1_StopCaptureRequest
#define onecollar_ble_v1_ToCollar_request_list_sessions_MSGTYPE onecollar_ble_v1_ListSessionsRequest
#define onecollar_ble_v1_ToCollar_request_read_session_MSGTYPE onecollar_ble_v1_ReadSessionRequest
#define onecollar_ble_v1_ToCollar_request_delete_session_MSGTYPE onecollar_ble_v1_DeleteSessionRequest
#define onecollar_ble_v1_ToCollar_request_label_tag_MSGTYPE onecollar_ble_v1_LabelTagRequest
#define onecollar_ble_v1_ToCollar_request_echo_MSGTYPE onecollar_ble_v1_EchoRequest
#define onecollar_ble_v1_ToCollar_request_test_pattern_MSGTYPE onecollar_ble_v1_TestPatternRequest
#define onecollar_ble_v1_ToCollar_request_get_debug_stats_MSGTYPE onecollar_ble_v1_GetDebugStatsRequest

#define onecollar_ble_v1_FromCollar_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,battery,response.battery),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,gps,response.gps),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,imu_snapshot,response.imu_snapshot),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,system_stats,response.system_stats),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,system_status,response.system_status),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,lora_status,response.lora_status),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,rf_status,response.rf_status),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,all_radios,response.all_radios),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,mtu_status,response.mtu_status),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,capabilities,response.capabilities),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,time_sync,response.time_sync),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,stream_status,response.stream_status),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,start_capture,response.start_capture),  70) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,session_list,response.session_list),  71) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,session_chunk,response.session_chunk),  72) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,echo,response.echo), 250) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,test_pattern,response.test_pattern), 251) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,debug_stats,response.debug_stats), 252)
#define onecollar_ble_v1_FromCollar_CALLBACK NULL
#define onecollar_ble_v1_FromCollar_DEFAULT NULL
#define onecollar_ble_v1_FromCollar_response_battery_MSGTYPE onecollar_ble_v1_BatteryStatus
#define onecollar_ble_v1_FromCollar_response_gps_MSGTYPE onecollar_ble_v1_GpsStatus
#define onecollar_ble_v1_FromCollar_response_imu_snapshot_MSGTYPE onecollar_ble_v1_ImuSnapshot
#define onecollar_ble_v1_FromCollar_response_system_stats_MSGTYPE onecollar_ble_v1_SystemStats
#define onecollar_ble_v1_FromCollar_response_system_status_MSGTYPE onecollar_ble_v1_SystemStatus
#define onecollar_ble_v1_FromCollar_response_lora_status_MSGTYPE onecollar_ble_v1_LoraStatus
#define onecollar_ble_v1_FromCollar_response_rf_status_MSGTYPE onecollar_ble_v1_RfStatus
#define onecollar_ble_v1_FromCollar_response_all_radios_MSGTYPE onecollar_ble_v1_AllRadiosStatus
#define onecollar_ble_v1_FromCollar_response_mtu_status_MSGTYPE onecollar_ble_v1_MtuStatus
#define onecollar_ble_v1_FromCollar_response_capabilities_MSGTYPE onecollar_ble_v1_Capabilities
#define onecollar_ble_v1_FromCollar_response_time_sync_MSGTYPE onecollar_ble_v1_TimeSyncResponse
#define onecollar_ble_v1_FromCollar_response_stream_status_MSGTYPE onecollar_ble_v1_StreamStatus
#define onecollar_ble_v1_FromCollar_response_start_capture_MSGTYPE onecollar_ble_v1_StartCaptureResponse
#define onecollar_ble_v1_FromCollar_response_session_list_MSGTYPE onecollar_ble_v1_SessionList
#define onecollar_ble_v1_FromCollar_response_session_chunk_MSGTYPE onecollar_ble_v1_SessionChunk
#define onecollar_ble_v1_FromCollar_response_echo_MSGTYPE onecollar_ble_v1_EchoResponse
#define onecollar_ble_v1_FromCollar_response_test_pattern_MSGTYPE onecollar_ble_v1_TestPatternResponse
#define onecollar_ble_v1_FromCollar_response_debug_stats_MSGTYPE onecollar_ble_v1_DebugStats

#define onecollar_ble_v1_Event_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,boundary_violation,event.boundary_violation),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,behavior_event,event.behavior_event),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,battery_low,event.battery_low),   3)
#define onecollar_ble_v1_Event_CALLBACK NULL
#define onecollar_ble_v1_Event_DEFAULT NULL
#define onecollar_ble_v1_Event_event_boundary_violation_MSGTYPE onecollar_ble_v1_BoundaryViolation
#define onecollar_ble_v1_Event_event_behavior_event_MSGTYPE onecollar_ble_v1_BehaviorEvent
#define onecollar_ble_v1_Event_event_battery_low_MSGTYPE onecollar_ble_v1_BatteryLow

#define onecollar_ble_v1_ImuBatch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, UINT64,   base_timestamp_us,   2) \
X(a, STATIC,   SINGULAR, UINT32,   rate_hz,           3) \
X(a, STATIC,   SINGULAR, UINT32,   sample_count,      4) \
X(a, STATIC,   SINGULAR, BYTES,    samples,           5)
#define onecollar_ble_v1_ImuBatch_CALLBACK NULL
#define onecollar_ble_v1_ImuBatch_DEFAULT NULL

#define onecollar_ble_v1_GetCapabilitiesRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetCapabilitiesRequest_CALLBACK NULL
#define onecollar_ble_v1_GetCapabilitiesRequest_DEFAULT NULL

#define onecollar_ble_v1_Capabilities_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   schema_major,      1) \
X(a, STATIC,   SINGULAR, UINT32,   schema_minor,      2) \
X(a, STATIC,   SINGULAR, UINT32,   min_app_supported_major,   3) \
X(a, STATIC,   SINGULAR, UINT32,   hw_revision,       4) \
X(a, STATIC,   REPEATED, MESSAGE,  capabilities,      5)
#define onecollar_ble_v1_Capabilities_CALLBACK NULL
#define onecollar_ble_v1_Capabilities_DEFAULT NULL
#define onecollar_ble_v1_Capabilities_capabilities_MSGTYPE onecollar_ble_v1_Capability

#define onecollar_ble_v1_Capability_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, STRING,   unlock_hint,       3)
#define onecollar_ble_v1_Capability_CALLBACK NULL
#define onecollar_ble_v1_Capability_DEFAULT NULL

#define onecollar_ble_v1_GetBatteryRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetBatteryRequest_CALLBACK NULL
#define onecollar_ble_v1_GetBatteryRequest_DEFAULT NULL

#define onecollar_ble_v1_BatteryStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   percentage,        1) \
X(a, STATIC,   SINGULAR, UINT32,   voltage_mv,        2) \
X(a, STATIC,   SINGULAR, UENUM,    charge,            3) \
X(a, STATIC,   SINGULAR, BOOL,     alert_active,      4) \
X(a, STATIC,   SINGULAR, UINT32,   alert_code,        5)
#define onecollar_ble_v1_BatteryStatus_CALLBACK NULL
#define onecollar_ble_v1_BatteryStatus_DEFAULT NULL

#define onecollar_ble_v1_GetGpsRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetGpsRequest_CALLBACK NULL
#define onecollar_ble_v1_GetGpsRequest_DEFAULT NULL

#define onecollar_ble_v1_GpsStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_fix,           1) \
X(a, STATIC,   SINGULAR, UINT32,   satellites,        2) \
X(a, STATIC,   SINGULAR, UENUM,    fix_quality,       3) \
X(a, STATIC,   SINGULAR, UINT32,   hdop_x10,          4) \
X(a, STATIC,   SINGULAR, SINT32,   latitude_udeg,     5) \
X(a, STATIC,   SINGULAR, SINT32,   longitude_udeg,    6) \
X(a, STATIC,   SINGULAR, SINT32,   altitude_m,        7) \
X(a, STATIC,   SINGULAR, UINT64,   fix_timestamp_us,   8)
#define onecollar_ble_v1_GpsStatus_CALLBACK NULL
#define onecollar_ble_v1_GpsStatus_DEFAULT NULL

#define onecollar_ble_v1_GetImuSnapshotRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetImuSnapshotRequest_CALLBACK NULL
#define onecollar_ble_v1_GetImuSnapshotRequest_DEFAULT NULL

#define onecollar_ble_v1_ImuSnapshot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      1) \
X(a, STATIC,   SINGULAR, SINT32,   accel_x_mg,        2) \
X(a, STATIC,   SINGULAR, SINT32,   accel_y_mg,        3) \
X(a, STATIC,   SINGULAR, SINT32,   accel_z_mg,        4) \
X(a, STATIC,   SINGULAR, SINT32,   gyro_x_mdps,       5) \
X(a, STATIC,   SINGULAR, SINT32,   gyro_y_mdps,       6) \
X(a, STATIC,   SINGULAR, SINT32,   gyro_z_mdps,       7)
#define onecollar_ble_v1_ImuSnapshot_CALLBACK NULL
#define onecollar_ble_v1_ImuSnapshot_DEFAULT NULL

#define onecollar_ble_v1_GetSystemStatsRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetSystemStatsRequest_CALLBACK NULL
#define onecollar_ble_v1_GetSystemStatsRequest_DEFAULT NULL

#define onecollar_ble_v1_SystemStats_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cpu_pct,           1) \
X(a, STATIC,   SINGULAR, UINT32,   task_count,        2) \
X(a, STATIC,   SINGULAR, UINT32,   free_heap_kb,      3) \
X(a, STATIC,   SINGULAR, UINT32,   min_free_heap_kb,   4) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_minutes,    5) \
X(a, STATIC,   SINGULAR, UINT32,   error_count,       6) \
X(a, STATIC,   SINGULAR, SINT32,   temperature_c,     7)
#define onecollar_ble_v1_SystemStats_CALLBACK NULL
#define onecollar_ble_v1_SystemStats_DEFAULT NULL

#define onecollar_ble_v1_GetSystemStatusRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetSystemStatusRequest_CALLBACK NULL
#define onecollar_ble_v1_GetSystemStatusRequest_DEFAULT NULL

#define onecollar_ble_v1_SystemStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   hw_revision,       2) \
X(a, STATIC,   SINGULAR, UINT64,   boot_time_us,      3) \
X(a, STATIC,   SINGULAR, UINT32,   capability_flags,   4)
#define onecollar_ble_v1_SystemStatus_CALLBACK NULL
#define onecollar_ble_v1_SystemStatus_DEFAULT NULL

#define onecollar_ble_v1_GetLoraStatusRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetLoraStatusRequest_CALLBACK NULL
#define onecollar_ble_v1_GetLoraStatusRequest_DEFAULT NULL

#define onecollar_ble_v1_LoraStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     available,         1) \
X(a, STATIC,   SINGULAR, BOOL,     active,            2) \
X(a, STATIC,   SINGULAR, SINT32,   rssi_dbm,          3) \
X(a, STATIC,   SINGULAR, UINT32,   packets_sent,      4) \
X(a, STATIC,   SINGULAR, UINT32,   packets_received,   5) \
X(a, STATIC,   SINGULAR, UINT32,   frequency_hz,      6) \
X(a, STATIC,   SINGULAR, UINT32,   spreading_factor,   7) \
X(a, STATIC,   SINGULAR, UINT32,   bandwidth_khz,     8)
#define onecollar_ble_v1_LoraStatus_CALLBACK NULL
#define onecollar_ble_v1_LoraStatus_DEFAULT NULL

#define onecollar_ble_v1_GetRfStatusRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetRfStatusRequest_CALLBACK NULL
#define onecollar_ble_v1_GetRfStatusRequest_DEFAULT NULL

#define onecollar_ble_v1_RfStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     available,         1) \
X(a, STATIC,   SINGULAR, BOOL,     active,            2) \
X(a, STATIC,   SINGULAR, SINT32,   rssi_dbm,          3) \
X(a, STATIC,   SINGULAR, UINT32,   frequency_hz,      4) \
X(a, STATIC,   SINGULAR, UINT32,   modulation,        5) \
X(a, STATIC,   SINGULAR, UINT32,   datarate_bps,      6)
#define onecollar_ble_v1_RfStatus_CALLBACK NULL
#define onecollar_ble_v1_RfStatus_DEFAULT NULL

#define onecollar_ble_v1_GetAllRadiosRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetAllRadiosRequest_CALLBACK NULL
#define onecollar_ble_v1_GetAllRadiosRequest_DEFAULT NULL

#define onecollar_ble_v1_AllRadiosStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ble,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lora,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rf,                3) \
X(a, STATIC,   SINGULAR, UINT32,   active_protocol,   4) \
X(a, STATIC,   SINGULAR, UINT64,   total_bytes_tx,    5) \
X(a, STATIC,   SINGULAR, UINT64,   total_bytes_rx,    6)
#define onecollar_ble_v1_AllRadiosStatus_CALLBACK NULL
#define onecollar_ble_v1_AllRadiosStatus_DEFAULT NULL
#define onecollar_ble_v1_AllRadiosStatus_ble_MSGTYPE onecollar_ble_v1_RadioSummary
#define onecollar_ble_v1_AllRadiosStatus_lora_MSGTYPE onecollar_ble_v1_RadioSummary
#define onecollar_ble_v1_AllRadiosStatus_rf_MSGTYPE onecollar_ble_v1_RadioSummary

#define onecollar_ble_v1_RadioSummary_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     available,         1) \
X(a, STATIC,   SINGULAR, BOOL,     active,            2) \
X(a, STATIC,   SINGULAR, SINT32,   rssi_dbm,          3)
#define onecollar_ble_v1_RadioSummary_CALLBACK NULL
#define onecollar_ble_v1_RadioSummary_DEFAULT NULL

#define onecollar_ble_v1_GetMtuStatusRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetMtuStatusRequest_CALLBACK NULL
#define onecollar_ble_v1_GetMtuStatusRequest_DEFAULT NULL

#define onecollar_ble_v1_MtuStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   negotiated_mtu,    1) \
X(a, STATIC,   SINGULAR, UINT32,   max_payload_size,   2)
#define onecollar_ble_v1_MtuStatus_CALLBACK NULL
#define onecollar_ble_v1_MtuStatus_DEFAULT NULL

#define onecollar_ble_v1_TimeSyncRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   phone_send_us,     1)
#define onecollar_ble_v1_TimeSyncRequest_CALLBACK NULL
#define onecollar_ble_v1_TimeSyncRequest_DEFAULT NULL

#define onecollar_ble_v1_TimeSyncResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   phone_send_us,     1) \
X(a, STATIC,   SINGULAR, UINT64,   collar_recv_us,    2) \
X(a, STATIC,   SINGULAR, UINT64,   collar_send_us,    3)
#define onecollar_ble_v1_TimeSyncResponse_CALLBACK NULL
#define onecollar_ble_v1_TimeSyncResponse_DEFAULT NULL

#define onecollar_ble_v1_StartImuStreamRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rate_hz,           1)
#define onecollar_ble_v1_StartImuStreamRequest_CALLBACK NULL
#define onecollar_ble_v1_StartImuStreamRequest_DEFAULT NULL

#define onecollar_ble_v1_StopImuStreamRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_StopImuStreamRequest_CALLBACK NULL
#define onecollar_ble_v1_StopImuStreamRequest_DEFAULT NULL

#define onecollar_ble_v1_GetImuBatchRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   start_timestamp_us,   1) \
X(a, STATIC,   SINGULAR, UINT64,   end_timestamp_us,   2)
#define onecollar_ble_v1_GetImuBatchRequest_CALLBACK NULL
#define onecollar_ble_v1_GetImuBatchRequest_DEFAULT NULL

#define onecollar_ble_v1_GetStreamStatusRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetStreamStatusRequest_CALLBACK NULL
#define onecollar_ble_v1_GetStreamStatusRequest_DEFAULT NULL

#define onecollar_ble_v1_StreamStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     running,           1) \
X(a, STATIC,   SINGULAR, UINT32,   rate_hz,           2) \
X(a, STATIC,   SINGULAR, UINT32,   batches_sent,      3) \
X(a, STATIC,   SINGULAR, UINT32,   samples_buffered,   4) \
X(a, STATIC,   SINGULAR, UINT32,   buffer_capacity,   5) \
X(a, STATIC,   SINGULAR, UINT32,   batches_dropped,   6)
#define onecollar_ble_v1_StreamStatus_CALLBACK NULL
#define onecollar_ble_v1_StreamStatus_DEFAULT NULL

#define onecollar_ble_v1_ResetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   delay_ms,          1)
#define onecollar_ble_v1_ResetRequest_CALLBACK NULL
#define onecollar_ble_v1_ResetRequest_DEFAULT NULL

#define onecollar_ble_v1_SetDebugLevelRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   level,             1)
#define onecollar_ble_v1_SetDebugLevelRequest_CALLBACK NULL
#define onecollar_ble_v1_SetDebugLevelRequest_DEFAULT NULL

#define onecollar_ble_v1_SetConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, BYTES,    value,             2)
#define onecollar_ble_v1_SetConfigRequest_CALLBACK NULL
#define onecollar_ble_v1_SetConfigRequest_DEFAULT NULL

#define onecollar_ble_v1_SetGeofenceRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   zone_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              3) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           4) \
X(a, STATIC,   REPEATED, MESSAGE,  points,            5)
#define onecollar_ble_v1_SetGeofenceRequest_CALLBACK NULL
#define onecollar_ble_v1_SetGeofenceRequest_DEFAULT NULL
#define onecollar_ble_v1_SetGeofenceRequest_points_MSGTYPE onecollar_ble_v1_GeofencePoint

#define onecollar_ble_v1_GeofencePoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   latitude_udeg,     1) \
X(a, STATIC,   SINGULAR, SINT32,   longitude_udeg,    2)
#define onecollar_ble_v1_GeofencePoint_CALLBACK NULL
#define onecollar_ble_v1_GeofencePoint_DEFAULT NULL

#define onecollar_ble_v1_SetWallClockRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   unix_us,           1)
#define onecollar_ble_v1_SetWallClockRequest_CALLBACK NULL
#define onecollar_ble_v1_SetWallClockRequest_DEFAULT NULL

#define onecollar_ble_v1_StartCaptureRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rate_hz,           1)
#define onecollar_ble_v1_StartCaptureRequest_CALLBACK NULL
#define onecollar_ble_v1_StartCaptureRequest_DEFAULT NULL

#define onecollar_ble_v1_StartCaptureResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT64,   start_time_us,     2)
#define onecollar_ble_v1_StartCaptureResponse_CALLBACK NULL
#define onecollar_ble_v1_StartCaptureResponse_DEFAULT NULL

#define onecollar_ble_v1_StopCaptureRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_StopCaptureRequest_CALLBACK NULL
#define onecollar_ble_v1_StopCaptureRequest_DEFAULT NULL

#define onecollar_ble_v1_ListSessionsRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_ListSessionsRequest_CALLBACK NULL
#define onecollar_ble_v1_ListSessionsRequest_DEFAULT NULL

#define onecollar_ble_v1_SessionList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  sessions,          1)
#define onecollar_ble_v1_SessionList_CALLBACK NULL
#define onecollar_ble_v1_SessionList_DEFAULT NULL
#define onecollar_ble_v1_SessionList_sessions_MSGTYPE onecollar_ble_v1_SessionSummary

#define onecollar_ble_v1_SessionSummary_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT64,   start_time_us,     2) \
X(a, STATIC,   SINGULAR, UINT64,   duration_us,       3) \
X(a, STATIC,   SINGULAR, UINT32,   sample_count,      4) \
X(a, STATIC,   SINGULAR, UINT32,   rate_hz,           5) \
X(a, STATIC,   SINGULAR, UINT32,   capability_flags,   6) \
X(a, STATIC,   SINGULAR, UINT64,   size_bytes,        7)
#define onecollar_ble_v1_SessionSummary_CALLBACK NULL
#define onecollar_ble_v1_SessionSummary_DEFAULT NULL

#define onecollar_ble_v1_ReadSessionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT64,   start_timestamp_us,   2) \
X(a, STATIC,   SINGULAR, UINT64,   end_timestamp_us,   3)
#define onecollar_ble_v1_ReadSessionRequest_CALLBACK NULL
#define onecollar_ble_v1_ReadSessionRequest_DEFAULT NULL

#define onecollar_ble_v1_SessionChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       2) \
X(a, STATIC,   SINGULAR, UINT64,   first_sample_us,   3) \
X(a, STATIC,   SINGULAR, UINT32,   rate_hz,           4) \
X(a, STATIC,   SINGULAR, UINT32,   sample_count,      5) \
X(a, STATIC,   SINGULAR, BYTES,    samples,           6) \
X(a, STATIC,   SINGULAR, BOOL,     final_chunk,       7)
#define onecollar_ble_v1_SessionChunk_CALLBACK NULL
#define onecollar_ble_v1_SessionChunk_DEFAULT NULL

#define onecollar_ble_v1_DeleteSessionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   session_id,        1)
#define onecollar_ble_v1_DeleteSessionRequest_CALLBACK NULL
#define onecollar_ble_v1_DeleteSessionRequest_DEFAULT NULL

#define onecollar_ble_v1_LabelTagRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   label,             1)
#define onecollar_ble_v1_LabelTagRequest_CALLBACK NULL
#define onecollar_ble_v1_LabelTagRequest_DEFAULT NULL

#define onecollar_ble_v1_BoundaryViolation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      1) \
X(a, STATIC,   SINGULAR, UINT32,   zone_id,           2) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              3) \
X(a, STATIC,   SINGULAR, SINT32,   latitude_udeg,     4) \
X(a, STATIC,   SINGULAR, SINT32,   longitude_udeg,    5) \
X(a, STATIC,   SINGULAR, UINT32,   distance_m,        6)
#define onecollar_ble_v1_BoundaryViolation_CALLBACK NULL
#define onecollar_ble_v1_BoundaryViolation_DEFAULT NULL

#define onecollar_ble_v1_BehaviorEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      1) \
X(a, STATIC,   SINGULAR, UINT32,   tree_id,           2) \
X(a, STATIC,   SINGULAR, UINT32,   class_id,          3) \
X(a, STATIC,   SINGULAR, UINT32,   confidence,        4)
#define onecollar_ble_v1_BehaviorEvent_CALLBACK NULL
#define onecollar_ble_v1_BehaviorEvent_DEFAULT NULL

#define onecollar_ble_v1_BatteryLow_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   percentage,        1) \
X(a, STATIC,   SINGULAR, UINT32,   voltage_mv,        2) \
X(a, STATIC,   SINGULAR, UENUM,    charge,            3)
#define onecollar_ble_v1_BatteryLow_CALLBACK NULL
#define onecollar_ble_v1_BatteryLow_DEFAULT NULL

#define onecollar_ble_v1_EchoRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           1)
#define onecollar_ble_v1_EchoRequest_CALLBACK NULL
#define onecollar_ble_v1_EchoRequest_DEFAULT NULL

#define onecollar_ble_v1_EchoResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           1)
#define onecollar_ble_v1_EchoResponse_CALLBACK NULL
#define onecollar_ble_v1_EchoResponse_DEFAULT NULL

#define onecollar_ble_v1_TestPatternRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pattern_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define onecollar_ble_v1_TestPatternRequest_CALLBACK NULL
#define onecollar_ble_v1_TestPatternRequest_DEFAULT NULL

#define onecollar_ble_v1_TestPatternResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pattern_id,        1) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           2)
#define onecollar_ble_v1_TestPatternResponse_CALLBACK NULL
#define onecollar_ble_v1_TestPatternResponse_DEFAULT NULL

#define onecollar_ble_v1_GetDebugStatsRequest_FIELDLIST(X, a) \

#define onecollar_ble_v1_GetDebugStatsRequest_CALLBACK NULL
#define onecollar_ble_v1_GetDebugStatsRequest_DEFAULT NULL

#define onecollar_ble_v1_DebugStats_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   commands_received,   1) \
X(a, STATIC,   SINGULAR, UINT64,   responses_sent,    2) \
X(a, STATIC,   SINGULAR, UINT64,   events_sent,       3) \
X(a, STATIC,   SINGULAR, UINT64,   bytes_received,    4) \
X(a, STATIC,   SINGULAR, UINT64,   bytes_sent,        5) \
X(a, STATIC,   SINGULAR, UINT64,   frame_errors,      6) \
X(a, STATIC,   SINGULAR, UINT64,   crc_errors,        7)
#define onecollar_ble_v1_DebugStats_CALLBACK NULL
#define onecollar_ble_v1_DebugStats_DEFAULT NULL

extern const pb_msgdesc_t onecollar_ble_v1_ToCollar_msg;
extern const pb_msgdesc_t onecollar_ble_v1_FromCollar_msg;
extern const pb_msgdesc_t onecollar_ble_v1_Event_msg;
extern const pb_msgdesc_t onecollar_ble_v1_ImuBatch_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetCapabilitiesRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_Capabilities_msg;
extern const pb_msgdesc_t onecollar_ble_v1_Capability_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetBatteryRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_BatteryStatus_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetGpsRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GpsStatus_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetImuSnapshotRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_ImuSnapshot_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetSystemStatsRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SystemStats_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetSystemStatusRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SystemStatus_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetLoraStatusRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_LoraStatus_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetRfStatusRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_RfStatus_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetAllRadiosRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_AllRadiosStatus_msg;
extern const pb_msgdesc_t onecollar_ble_v1_RadioSummary_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetMtuStatusRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_MtuStatus_msg;
extern const pb_msgdesc_t onecollar_ble_v1_TimeSyncRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_TimeSyncResponse_msg;
extern const pb_msgdesc_t onecollar_ble_v1_StartImuStreamRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_StopImuStreamRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetImuBatchRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetStreamStatusRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_StreamStatus_msg;
extern const pb_msgdesc_t onecollar_ble_v1_ResetRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SetDebugLevelRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SetConfigRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SetGeofenceRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GeofencePoint_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SetWallClockRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_StartCaptureRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_StartCaptureResponse_msg;
extern const pb_msgdesc_t onecollar_ble_v1_StopCaptureRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_ListSessionsRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SessionList_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SessionSummary_msg;
extern const pb_msgdesc_t onecollar_ble_v1_ReadSessionRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_SessionChunk_msg;
extern const pb_msgdesc_t onecollar_ble_v1_DeleteSessionRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_LabelTagRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_BoundaryViolation_msg;
extern const pb_msgdesc_t onecollar_ble_v1_BehaviorEvent_msg;
extern const pb_msgdesc_t onecollar_ble_v1_BatteryLow_msg;
extern const pb_msgdesc_t onecollar_ble_v1_EchoRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_EchoResponse_msg;
extern const pb_msgdesc_t onecollar_ble_v1_TestPatternRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_TestPatternResponse_msg;
extern const pb_msgdesc_t onecollar_ble_v1_GetDebugStatsRequest_msg;
extern const pb_msgdesc_t onecollar_ble_v1_DebugStats_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define onecollar_ble_v1_ToCollar_fields &onecollar_ble_v1_ToCollar_msg
#define onecollar_ble_v1_FromCollar_fields &onecollar_ble_v1_FromCollar_msg
#define onecollar_ble_v1_Event_fields &onecollar_ble_v1_Event_msg
#define onecollar_ble_v1_ImuBatch_fields &onecollar_ble_v1_ImuBatch_msg
#define onecollar_ble_v1_GetCapabilitiesRequest_fields &onecollar_ble_v1_GetCapabilitiesRequest_msg
#define onecollar_ble_v1_Capabilities_fields &onecollar_ble_v1_Capabilities_msg
#define onecollar_ble_v1_Capability_fields &onecollar_ble_v1_Capability_msg
#define onecollar_ble_v1_GetBatteryRequest_fields &onecollar_ble_v1_GetBatteryRequest_msg
#define onecollar_ble_v1_BatteryStatus_fields &onecollar_ble_v1_BatteryStatus_msg
#define onecollar_ble_v1_GetGpsRequest_fields &onecollar_ble_v1_GetGpsRequest_msg
#define onecollar_ble_v1_GpsStatus_fields &onecollar_ble_v1_GpsStatus_msg
#define onecollar_ble_v1_GetImuSnapshotRequest_fields &onecollar_ble_v1_GetImuSnapshotRequest_msg
#define onecollar_ble_v1_ImuSnapshot_fields &onecollar_ble_v1_ImuSnapshot_msg
#define onecollar_ble_v1_GetSystemStatsRequest_fields &onecollar_ble_v1_GetSystemStatsRequest_msg
#define onecollar_ble_v1_SystemStats_fields &onecollar_ble_v1_SystemStats_msg
#define onecollar_ble_v1_GetSystemStatusRequest_fields &onecollar_ble_v1_GetSystemStatusRequest_msg
#define onecollar_ble_v1_SystemStatus_fields &onecollar_ble_v1_SystemStatus_msg
#define onecollar_ble_v1_GetLoraStatusRequest_fields &onecollar_ble_v1_GetLoraStatusRequest_msg
#define onecollar_ble_v1_LoraStatus_fields &onecollar_ble_v1_LoraStatus_msg
#define onecollar_ble_v1_GetRfStatusRequest_fields &onecollar_ble_v1_GetRfStatusRequest_msg
#define onecollar_ble_v1_RfStatus_fields &onecollar_ble_v1_RfStatus_msg
#define onecollar_ble_v1_GetAllRadiosRequest_fields &onecollar_ble_v1_GetAllRadiosRequest_msg
#define onecollar_ble_v1_AllRadiosStatus_fields &onecollar_ble_v1_AllRadiosStatus_msg
#define onecollar_ble_v1_RadioSummary_fields &onecollar_ble_v1_RadioSummary_msg
#define onecollar_ble_v1_GetMtuStatusRequest_fields &onecollar_ble_v1_GetMtuStatusRequest_msg
#define onecollar_ble_v1_MtuStatus_fields &onecollar_ble_v1_MtuStatus_msg
#define onecollar_ble_v1_TimeSyncRequest_fields &onecollar_ble_v1_TimeSyncRequest_msg
#define onecollar_ble_v1_TimeSyncResponse_fields &onecollar_ble_v1_TimeSyncResponse_msg
#define onecollar_ble_v1_StartImuStreamRequest_fields &onecollar_ble_v1_StartImuStreamRequest_msg
#define onecollar_ble_v1_StopImuStreamRequest_fields &onecollar_ble_v1_StopImuStreamRequest_msg
#define onecollar_ble_v1_GetImuBatchRequest_fields &onecollar_ble_v1_GetImuBatchRequest_msg
#define onecollar_ble_v1_GetStreamStatusRequest_fields &onecollar_ble_v1_GetStreamStatusRequest_msg
#define onecollar_ble_v1_StreamStatus_fields &onecollar_ble_v1_StreamStatus_msg
#define onecollar_ble_v1_ResetRequest_fields &onecollar_ble_v1_ResetRequest_msg
#define onecollar_ble_v1_SetDebugLevelRequest_fields &onecollar_ble_v1_SetDebugLevelRequest_msg
#define onecollar_ble_v1_SetConfigRequest_fields &onecollar_ble_v1_SetConfigRequest_msg
#define onecollar_ble_v1_SetGeofenceRequest_fields &onecollar_ble_v1_SetGeofenceRequest_msg
#define onecollar_ble_v1_GeofencePoint_fields &onecollar_ble_v1_GeofencePoint_msg
#define onecollar_ble_v1_SetWallClockRequest_fields &onecollar_ble_v1_SetWallClockRequest_msg
#define onecollar_ble_v1_StartCaptureRequest_fields &onecollar_ble_v1_StartCaptureRequest_msg
#define onecollar_ble_v1_StartCaptureResponse_fields &onecollar_ble_v1_StartCaptureResponse_msg
#define onecollar_ble_v1_StopCaptureRequest_fields &onecollar_ble_v1_StopCaptureRequest_msg
#define onecollar_ble_v1_ListSessionsRequest_fields &onecollar_ble_v1_ListSessionsRequest_msg
#define onecollar_ble_v1_SessionList_fields &onecollar_ble_v1_SessionList_msg
#define onecollar_ble_v1_SessionSummary_fields &onecollar_ble_v1_SessionSummary_msg
#define onecollar_ble_v1_ReadSessionRequest_fields &onecollar_ble_v1_ReadSessionRequest_msg
#define onecollar_ble_v1_SessionChunk_fields &onecollar_ble_v1_SessionChunk_msg
#define onecollar_ble_v1_DeleteSessionRequest_fields &onecollar_ble_v1_DeleteSessionRequest_msg
#define onecollar_ble_v1_LabelTagRequest_fields &onecollar_ble_v1_LabelTagRequest_msg
#define onecollar_ble_v1_BoundaryViolation_fields &onecollar_ble_v1_BoundaryViolation_msg
#define onecollar_ble_v1_BehaviorEvent_fields &onecollar_ble_v1_BehaviorEvent_msg
#define onecollar_ble_v1_BatteryLow_fields &onecollar_ble_v1_BatteryLow_msg
#define onecollar_ble_v1_EchoRequest_fields &onecollar_ble_v1_EchoRequest_msg
#define onecollar_ble_v1_EchoResponse_fields &onecollar_ble_v1_EchoResponse_msg
#define onecollar_ble_v1_TestPatternRequest_fields &onecollar_ble_v1_TestPatternRequest_msg
#define onecollar_ble_v1_TestPatternResponse_fields &onecollar_ble_v1_TestPatternResponse_msg
#define onecollar_ble_v1_GetDebugStatsRequest_fields &onecollar_ble_v1_GetDebugStatsRequest_msg
#define onecollar_ble_v1_DebugStats_fields &onecollar_ble_v1_DebugStats_msg

/* Maximum encoded size of messages (where known) */
#define ONECOLLAR_BLE_V1_BLE_PROTOCOL_PB_H_MAX_SIZE onecollar_ble_v1_FromCollar_size
#define onecollar_ble_v1_AllRadiosStatus_size    64
#define onecollar_ble_v1_BatteryLow_size         14
#define onecollar_ble_v1_BatteryStatus_size      22
#define onecollar_ble_v1_BehaviorEvent_size      29
#define onecollar_ble_v1_BoundaryViolation_size  37
#define onecollar_ble_v1_Capabilities_size       5400
#define onecollar_ble_v1_Capability_size         165
#define onecollar_ble_v1_DebugStats_size         77
#define onecollar_ble_v1_DeleteSessionRequest_size 11
#define onecollar_ble_v1_EchoRequest_size        259
#define onecollar_ble_v1_EchoResponse_size       259
#define onecollar_ble_v1_Event_size              39
#define onecollar_ble_v1_FromCollar_size         5406
#define onecollar_ble_v1_GeofencePoint_size      12
#define onecollar_ble_v1_GetAllRadiosRequest_size 0
#define onecollar_ble_v1_GetBatteryRequest_size  0
#define onecollar_ble_v1_GetCapabilitiesRequest_size 0
#define onecollar_ble_v1_GetDebugStatsRequest_size 0
#define onecollar_ble_v1_GetGpsRequest_size      0
#define onecollar_ble_v1_GetImuBatchRequest_size 22
#define onecollar_ble_v1_GetImuSnapshotRequest_size 0
#define onecollar_ble_v1_GetLoraStatusRequest_size 0
#define onecollar_ble_v1_GetMtuStatusRequest_size 0
#define onecollar_ble_v1_GetRfStatusRequest_size 0
#define onecollar_ble_v1_GetStreamStatusRequest_size 0
#define onecollar_ble_v1_GetSystemStatsRequest_size 0
#define onecollar_ble_v1_GetSystemStatusRequest_size 0
#define onecollar_ble_v1_GpsStatus_size          45
#define onecollar_ble_v1_ImuBatch_size           512
#define onecollar_ble_v1_ImuSnapshot_size        47
#define onecollar_ble_v1_LabelTagRequest_size    65
#define onecollar_ble_v1_ListSessionsRequest_size 0
#define onecollar_ble_v1_LoraStatus_size         40
#define onecollar_ble_v1_MtuStatus_size          12
#define onecollar_ble_v1_RadioSummary_size       10
#define onecollar_ble_v1_ReadSessionRequest_size 33
#define onecollar_ble_v1_ResetRequest_size       6
#define onecollar_ble_v1_RfStatus_size           28
#define onecollar_ble_v1_SessionChunk_size       525
#define onecollar_ble_v1_SessionList_size        2048
#define onecollar_ble_v1_SessionSummary_size     62
#define onecollar_ble_v1_SetConfigRequest_size   292
#define onecollar_ble_v1_SetDebugLevelRequest_size 6
#define onecollar_ble_v1_SetGeofenceRequest_size 475
#define onecollar_ble_v1_SetWallClockRequest_size 11
#define onecollar_ble_v1_StartCaptureRequest_size 6
#define onecollar_ble_v1_StartCaptureResponse_size 22
#define onecollar_ble_v1_StartImuStreamRequest_size 6
#define onecollar_ble_v1_StopCaptureRequest_size 0
#define onecollar_ble_v1_StopImuStreamRequest_size 0
#define onecollar_ble_v1_StreamStatus_size       32
#define onecollar_ble_v1_SystemStats_size        42
#define onecollar_ble_v1_SystemStatus_size       56
#define onecollar_ble_v1_TestPatternRequest_size 12
#define onecollar_ble_v1_TestPatternResponse_size 265
#define onecollar_ble_v1_TimeSyncRequest_size    11
#define onecollar_ble_v1_TimeSyncResponse_size   33
#define onecollar_ble_v1_ToCollar_size           479

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
